"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Icon } from "@/components/icons";
import { PageHeader } from "@/components/page-header";
import { apiFetch, ApiError } from "@/lib/api";

type Config = { task_type: string; provider_name: string; model_name: string; base_url: string; credential_ref: string; status: string; timeout_ms: number; parameters: unknown };
type ProviderBreakdown = { capability: string; provider_name: string; model_name: string; calls: number; failures: number; error_rate: number; avg_latency_ms: number; input_tokens: number; output_tokens: number; estimated_cost: number };
type SlowQuery = { id: string; question: string; answer_status: string; generation_provider?: string; latency_ms: number; citation_count: number; citation_coverage?: number; source_count: number; embedding_ms: number; retrieval_ms: number; rerank_ms: number; generation_ms: number; created_at: string };
type Metrics = {
  windowHours: number; generatedAt: string; costConfigured: boolean;
  summary: { calls: number; avg_latency_ms: number; failures: number; failure_rate: number; input_tokens: number; output_tokens: number; estimated_cost: number; usage_calls: number; costed_calls: number };
  rag: Record<string, number> & { rag_queries: number; succeeded: number; no_evidence: number; p95_latency_ms: number; avg_citation_coverage: number; avg_source_count: number; conflict_runs: number; assessed_evidence: number };
  index: { indexed_documents: number; chunks: number; vectorized_chunks: number; indexed_sources: number; missing_source_time: number };
  providerBreakdown: ProviderBreakdown[];
  latencyTrend: Array<{ bucket: string; queries: number; avg_latency_ms: number; p95_latency_ms: number; no_evidence: number }>;
  noEvidenceReasons: Array<{ reason: string; occurrences: number }>;
  slowQueries: SlowQuery[];
};
type Evaluation = { id: string; name: string; capability: string; status: string; metrics: string | Record<string, unknown>; passed: boolean; started_at: string; completed_at?: string };
type EvaluationFilter = "ALL" | "PASS" | "FAIL";

const STAGES = [
  ["Embedding", "avg_embedding_ms", "p95_embedding_ms"],
  ["混合召回", "avg_retrieval_ms", "p95_retrieval_ms"],
  ["Rerank", "avg_rerank_ms", "p95_rerank_ms"],
  ["Generation", "avg_generation_ms", "p95_generation_ms"],
] as const;

export default function AdminModelsPage() {
  const [configs,setConfigs]=useState<Config[]>([]); const [metrics,setMetrics]=useState<Metrics|null>(null); const [evaluations,setEvaluations]=useState<Evaluation[]>([]);
  const [windowHours,setWindowHours]=useState(24); const [evaluationFilter,setEvaluationFilter]=useState<EvaluationFilter>("ALL"); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true);
  const loadMetrics=useCallback(async(hours:number)=>setMetrics(await apiFetch<Metrics>(`/admin/ai/metrics?hours=${hours}`)),[]);
  const loadEvaluations=useCallback(async(filter:EvaluationFilter)=>{const query=filter==="ALL"?"":"&passed="+(filter==="PASS");setEvaluations(await apiFetch<Evaluation[]>(`/admin/ai/evaluations?limit=30${query}`));},[]);
  const load=useCallback(async()=>{setLoading(true);try{const [c]=await Promise.all([apiFetch<Config[]>("/admin/ai/configs"),loadMetrics(windowHours),loadEvaluations(evaluationFilter)]);setConfigs(c);}catch(error){setNotice(message(error));}finally{setLoading(false);}},[evaluationFilter,loadEvaluations,loadMetrics,windowHours]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  async function save(config:Config){setBusy(true);try{await apiFetch("/admin/ai/configs",{method:"PUT",body:JSON.stringify({taskType:config.task_type,providerName:config.provider_name,modelName:config.model_name,baseUrl:config.base_url,credentialRef:config.credential_ref,status:config.status,timeoutMs:config.timeout_ms,parametersJson:typeof config.parameters==="string"?config.parameters:JSON.stringify(config.parameters??{})})});setNotice(`${config.task_type} 配置已保存；密钥仍只引用环境变量。`);await load();}catch(error){setNotice(message(error));}finally{setBusy(false);}}
  async function operation(path:string,label:string){setBusy(true);try{await apiFetch<Record<string,unknown>>(path,{method:"POST"});setNotice(`${label}完成，监控数据已刷新。`);await load();}catch(error){setNotice(message(error));}finally{setBusy(false);}}
  function updateConfig(index:number,key:keyof Config,value:unknown){setConfigs(values=>values.map((item,itemIndex)=>itemIndex===index?{...item,[key]:value}:item));}
  function updatePricing(index:number,key:"inputCostPerMillion"|"outputCostPerMillion",value:string){setConfigs(values=>values.map((item,itemIndex)=>{if(itemIndex!==index)return item;const parameters=configParameters(item.parameters);if(value.trim()==="")delete parameters[key];else parameters[key]=Number(value);return {...item,parameters:JSON.stringify(parameters)};}));}
  const maxStage=useMemo(()=>Math.max(1,...STAGES.map(([, ,p95])=>Number(metrics?.rag[p95]??0))),[metrics]);
  const maxTrend=useMemo(()=>Math.max(1,...(metrics?.latencyTrend??[]).map(point=>Number(point.p95_latency_ms))),[metrics]);
  return <div className="page-shell rag-admin-page"><PageHeader title="RAG 配置、评测与监控" description="从查询延迟到证据质量，再到 Provider 用量与失败降级，统一查看真实运行数据。" action={<div className="header-actions"><button className="button" disabled={busy} onClick={()=>void operation("/admin/ai/smoke","Provider 烟测")}>模型烟测</button><button className="button" disabled={busy} onClick={()=>void operation("/admin/ai/reindex","索引更新")}>更新索引</button><button className="button primary" disabled={busy} onClick={()=>void operation("/admin/ai/evaluations/run","黄金集评测")}>运行评测</button></div>}/>
    <div className="observability-toolbar"><div><span className={`live-dot ${loading?"loading":""}`} />{loading?"正在同步":"数据已同步"}<small>{metrics?.generatedAt?new Date(metrics.generatedAt).toLocaleString("zh-CN"):"—"}</small></div><label>观察窗口<select aria-label="观察窗口" value={windowHours} onChange={event=>setWindowHours(Number(event.target.value))}><option value={24}>最近 24 小时</option><option value={72}>最近 3 天</option><option value={168}>最近 7 天</option></select></label><button className="icon-refresh" aria-label="刷新监控" onClick={()=>void load()} disabled={loading}><Icon name="history" /></button></div>
    {notice&&<div className="notice" role="status">{notice}<button aria-label="关闭提示" onClick={()=>setNotice("")}>×</button></div>}

    <section className="rag-kpi-strip" aria-label="RAG 核心指标">
      <Kpi value={metrics?.rag.rag_queries??0} label="研究查询" meta={`${metrics?.rag.succeeded??0} 次成功`} />
      <Kpi value={`${formatNumber(metrics?.rag.comparable_p95_latency_ms??metrics?.rag.p95_latency_ms)} ms`} label="P95 可比延迟" meta={`${formatNumber(metrics?.rag.comparable_queries)} 个当前配置样本 · 全窗口 ${formatNumber(metrics?.rag.p95_latency_ms)} ms`} state={(metrics?.rag.comparable_p95_latency_ms??metrics?.rag.p95_latency_ms??0)<=12000?"good":"warn"} />
      <Kpi value={`${Math.round((metrics?.rag.avg_citation_coverage??0)*100)}%`} label="引用覆盖" meta={`${formatNumber(metrics?.rag.avg_source_count,1)} 个平均信源`} state={(metrics?.rag.avg_citation_coverage??0)>=.8?"good":"warn"} />
      <Kpi value={`${formatNumber(metrics?.summary.failure_rate,2)}%`} label="Provider 错误率" meta={`${metrics?.summary.failures??0} / ${metrics?.summary.calls??0} 次`} state={(metrics?.summary.failures??0)===0?"good":"warn"} />
      <Kpi value={metrics?.costConfigured?formatCost(metrics?.summary.estimated_cost):"待配置"} label="估算成本" meta={metrics?.costConfigured?`${formatNumber((metrics?.summary.input_tokens??0)+(metrics?.summary.output_tokens??0))} tokens`:"需配置每百万 Token 单价"} />
    </section>

    <div className="rag-dashboard-grid">
      <section className="product-panel stage-latency-panel"><PanelHeader eyebrow="LATENCY BREAKDOWN" title="各阶段延迟" note="均值 / P95" /><div className="stage-bars">{STAGES.map(([label,averageKey,p95Key])=>{const average=Number(metrics?.rag[averageKey]??0);const p95=Number(metrics?.rag[p95Key]??0);return <div className="stage-row" key={label}><div><strong>{label}</strong><span>{formatNumber(average)} / {formatNumber(p95)} ms</span></div><div className="stage-track"><i style={{width:`${Math.max(2,p95/maxStage*100)}%`}} /><b style={{width:`${Math.max(1,average/maxStage*100)}%`}} /></div></div>;})}</div><div className="stage-legend"><span><i />P95</span><span><i />均值</span></div></section>
      <section className="product-panel latency-trend-panel"><PanelHeader eyebrow={`TREND · ${windowHours}H`} title="查询延迟趋势" note={`${metrics?.rag.no_evidence??0} 次无证据`} /><div className="latency-chart" aria-label="按小时查询延迟">{(metrics?.latencyTrend??[]).map(point=><div className="trend-column" title={`${point.bucket} · P95 ${point.p95_latency_ms}ms · ${point.queries} 次`} key={point.bucket}><div><i style={{height:`${Math.max(3,point.p95_latency_ms/maxTrend*100)}%`}} /><b style={{height:`${Math.max(2,point.avg_latency_ms/maxTrend*100)}%`}} /></div><span>{point.bucket.slice(-5)}</span></div>)}</div></section>
    </div>

    <div className="rag-dashboard-grid lower">
      <section className="product-panel provider-health"><PanelHeader eyebrow="PROVIDER HEALTH" title="调用质量与用量" note={`${formatNumber((metrics?.summary.input_tokens??0)+(metrics?.summary.output_tokens??0))} tokens`} /><div className="provider-list">{(metrics?.providerBreakdown??[]).map(provider=><article key={`${provider.capability}-${provider.provider_name}-${provider.model_name}`}><div><strong>{provider.capability}</strong><span>{provider.provider_name} · {provider.model_name}</span></div><dl><div><dt>调用</dt><dd>{provider.calls}</dd></div><div><dt>错误率</dt><dd className={provider.failures?"danger":""}>{formatNumber(provider.error_rate,2)}%</dd></div><div><dt>均值</dt><dd>{formatNumber(provider.avg_latency_ms)}ms</dd></div><div><dt>Tokens</dt><dd>{formatNumber(provider.input_tokens+provider.output_tokens)}</dd></div></dl></article>)}</div></section>
      <section className="product-panel evidence-health"><PanelHeader eyebrow="EVIDENCE HEALTH" title="无证据与索引护栏" note={`${metrics?.rag.assessed_evidence??0} 条已裁决证据`} /><div className="index-guardrails"><div><strong>{formatNumber(metrics?.index.vectorized_chunks)}</strong><span>向量 Chunk / {formatNumber(metrics?.index.chunks)}</span></div><div><strong>{formatNumber(metrics?.index.indexed_sources)}</strong><span>索引信源</span></div><div><strong>{formatNumber(metrics?.index.missing_source_time)}</strong><span>缺原始时间</span></div><div><strong>{formatNumber(metrics?.rag.conflict_runs)}</strong><span>冲突查询</span></div></div><div className="reason-list">{(metrics?.noEvidenceReasons??[]).length?(metrics?.noEvidenceReasons??[]).map(item=><div key={item.reason}><span>{reasonLabel(item.reason)}</span><strong>{item.occurrences}</strong></div>):<div className="empty-compact">当前窗口没有无证据查询</div>}</div></section>
    </div>

    <section className="product-panel slow-query-panel"><PanelHeader eyebrow="SLOW QUERY SAMPLES" title="慢查询诊断" note="优先展示 ≥12 秒，其次按延迟排序" /><div className="slow-query-table"><div className="slow-query-row head"><span>问题 / 时间</span><span>总延迟</span><span>主要瓶颈</span><span>证据</span><span>状态</span></div>{(metrics?.slowQueries??[]).map(query=><div className={`slow-query-row ${query.latency_ms>=12000?"is-slow":""}`} key={query.id}><span><strong title={query.question}>{query.question}</strong><small>{new Date(query.created_at).toLocaleString("zh-CN")}</small></span><span>{formatNumber(query.latency_ms)} ms</span><span>{bottleneck(query)}</span><span>{query.source_count} 信源 · {query.citation_count} 引用</span><span className={`status-badge ${query.answer_status==="SUCCEEDED"?"active":"failed"}`}>{query.answer_status}</span></div>)}</div></section>

    <section className="product-panel evaluation-panel"><header><div><span className="overline">EVALUATION HISTORY</span><h2>黄金集评测历史</h2></div><div className="evaluation-filters" aria-label="评测结果筛选">{(["ALL","PASS","FAIL"] as EvaluationFilter[]).map(filter=><button className={evaluationFilter===filter?"active":""} onClick={()=>setEvaluationFilter(filter)} key={filter}>{filter==="ALL"?"全部":filter}</button>)}</div></header><div className="evaluation-list">{evaluations.map(evaluation=>{const values=evaluationMetrics(evaluation.metrics);return <article key={evaluation.id}><div><span className={`status-badge ${evaluation.passed?"active":"failed"}`}>{evaluation.passed?"PASS":"FAIL"}</span><strong>{evaluation.name}</strong><small>{new Date(evaluation.started_at).toLocaleString("zh-CN")} · {splitSummary(values)}</small></div><dl><MetricTerm label="Hit@5" value={percent(values.hitAt5)} /><MetricTerm label="Precision@8" value={percent(values.precisionAt8)} /><MetricTerm label="MRR@10" value={percent(values.mrrAt10)} /><MetricTerm label="拒答准确率" value={percent(values.refusalAccuracy)} /><MetricTerm label="Recall@20" value={percent(values.recallAt20)} /><MetricTerm label="nDCG@10" value={percent(values.ndcgAt10)} /><MetricTerm label="结构失败" value={percent(values.structuredOutputFailureRate)} /></dl></article>;})}</div></section>

    <section className="config-section"><div className="section-heading"><div><span className="overline">RUNTIME CONFIG</span><h2>Provider 配置</h2></div><p>价格仅用于本地成本估算；密钥值不会进入数据库或页面。</p></div><div className="admin-ai-grid">{configs.map((config,index)=>{const pricing=configParameters(config.parameters);return <article className="product-panel ai-config-card" key={config.task_type}><header><div><span className="overline">{config.task_type}</span><h2>{config.provider_name}</h2></div><span className={`status-badge ${config.status==="ACTIVE"?"active":""}`}>{config.status}</span></header><label>模型<input value={config.model_name??""} onChange={event=>updateConfig(index,"model_name",event.target.value)} /></label><label>服务地址<input value={config.base_url??""} onChange={event=>updateConfig(index,"base_url",event.target.value)} /></label><label>密钥环境变量<input value={config.credential_ref??""} onChange={event=>updateConfig(index,"credential_ref",event.target.value)} /></label>{config.task_type==="RAG_GENERATION"?<div className="pricing-grid"><label>输入单价 / 百万 Token<input type="number" min="0" step="0.000001" value={String(pricing.inputCostPerMillion??"")} onChange={event=>updatePricing(index,"inputCostPerMillion",event.target.value)} placeholder="未配置" /></label><label>输出单价 / 百万 Token<input type="number" min="0" step="0.000001" value={String(pricing.outputCostPerMillion??"")} onChange={event=>updatePricing(index,"outputCostPerMillion",event.target.value)} placeholder="未配置" /></label></div>:null}<label>状态<select value={config.status} onChange={event=>updateConfig(index,"status",event.target.value)}><option>DISABLED</option><option>ACTIVE</option></select></label><button className="button primary" disabled={busy} onClick={()=>void save(config)}>保存配置</button></article>;})}</div></section>
  </div>;
}

function Kpi({value,label,meta,state}:{value:string|number;label:string;meta:string;state?:"good"|"warn"}){return <article className={state??""}><span>{label}</span><strong>{value}</strong><small>{meta}</small></article>;}
function PanelHeader({eyebrow,title,note}:{eyebrow:string;title:string;note:string}){return <header><div><span className="overline">{eyebrow}</span><h2>{title}</h2></div><span>{note}</span></header>;}
function MetricTerm({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>;}
function formatNumber(value:unknown,digits=0){const numeric=Number(value??0);return Number.isFinite(numeric)?new Intl.NumberFormat("zh-CN",{maximumFractionDigits:digits}).format(numeric):"0";}
function formatCost(value:unknown){return new Intl.NumberFormat("zh-CN",{minimumFractionDigits:4,maximumFractionDigits:6}).format(Number(value??0));}
function percent(value:unknown){return `${formatNumber(Number(value??0)*100,1)}%`;}
function evaluationMetrics(value:Evaluation["metrics"]){if(typeof value!=="string")return value;try{return JSON.parse(value) as Record<string,unknown>;}catch{return {};}}
function splitSummary(values:Record<string,unknown>){const groups=values.bySplit as Record<string,Record<string,unknown>>|undefined;if(!groups)return String(values.split??"ALL");return ["DEV","TEST","CANARY"].filter(key=>groups[key]).map(key=>`${key} ${percent(groups[key].passRate)}`).join(" · ");}
function configParameters(value:unknown):Record<string,number>{if(typeof value==="string"){try{return JSON.parse(value) as Record<string,number>;}catch{return {};}}return value&&typeof value==="object"?{...(value as Record<string,number>)}:{};}
function bottleneck(query:SlowQuery){const values:[[string,number],[string,number],[string,number],[string,number]]=[["Embedding",query.embedding_ms],["召回",query.retrieval_ms],["Rerank",query.rerank_ms],["Generation",query.generation_ms]];return values.sort((left,right)=>right[1]-left[1])[0][0];}
function reasonLabel(reason:string){return ({OFFICIAL_SCOPE_NO_MATCH:"官方范围无匹配",TIME_RANGE_NO_MATCH:"时间窗口无匹配",SOURCE_TYPE_NO_MATCH:"来源类型无匹配",NO_RELEVANT_CHUNK:"没有相关 Chunk",RERANK_NO_RELEVANT:"重排后无相关证据",DIVERSITY_FILTERED:"多样化后无证据",LEGACY_UNCLASSIFIED:"旧记录未分类"} as Record<string,string>)[reason]??reason;}
function message(error:unknown){return error instanceof ApiError?error.message:error instanceof Error?error.message:"请求失败";}
