"use client";
import { useCallback, useEffect, useState } from "react";
import { PageHeader } from "@/components/page-header";
import { apiFetch, ApiError } from "@/lib/api";

type Config = { task_type: string; provider_name: string; model_name: string; base_url: string; credential_ref: string; status: string; timeout_ms: number; parameters: unknown };
type Metrics = { summary: { calls: number; avg_latency_ms: number; failures: number; estimated_cost: number }; rag: { rag_queries: number; succeeded: number; no_evidence: number; avg_latency_ms: number; p95_latency_ms: number; avg_citation_coverage: number; avg_source_count: number; avg_context_count: number }; index: { indexed_documents: number; chunks: number; vectorized_chunks: number; indexed_sources: number; missing_source_time: number }; recent: Array<Record<string, unknown>> };
type Evaluation = { id: string; name: string; capability: string; status: string; metrics: Record<string, number>; passed: boolean; started_at: string };
export default function AdminModelsPage() {
  const [configs,setConfigs]=useState<Config[]>([]); const [metrics,setMetrics]=useState<Metrics|null>(null); const [evaluations,setEvaluations]=useState<Evaluation[]>([]); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{try{const [c,m,e]=await Promise.all([apiFetch<Config[]>("/admin/ai/configs"),apiFetch<Metrics>("/admin/ai/metrics"),apiFetch<Evaluation[]>("/admin/ai/evaluations")]);setConfigs(c);setMetrics(m);setEvaluations(e);}catch(e){setNotice(message(e));}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  async function save(config:Config){setBusy(true);try{await apiFetch("/admin/ai/configs",{method:"PUT",body:JSON.stringify({taskType:config.task_type,providerName:config.provider_name,modelName:config.model_name,baseUrl:config.base_url,credentialRef:config.credential_ref,status:config.status,timeoutMs:config.timeout_ms,parametersJson:typeof config.parameters==="string"?config.parameters:JSON.stringify(config.parameters??{})})});setNotice(`${config.task_type} 配置已保存；密钥仅引用环境变量名称。`);await load();}catch(e){setNotice(message(e));}finally{setBusy(false);}}
  async function operation(path:string,label:string){setBusy(true);try{const result=await apiFetch<Record<string,unknown>>(path,{method:"POST"});setNotice(`${label}完成：${JSON.stringify(result)}`);await load();}catch(e){setNotice(message(e));}finally{setBusy(false);}}
  return <div className="page-shell"><PageHeader title="RAG 配置、评测与监控" description="统一管理 Generation / Embedding / Rerank Provider，并用发布门禁阻止 Mock 和越权引用。" action={<div className="header-actions"><button className="button" disabled={busy} onClick={()=>void operation("/admin/ai/smoke","Provider 烟测")}>测试模型连接</button><button className="button" disabled={busy} onClick={()=>void operation("/admin/ai/reprocess?limit=100","隔离内容重分析排队")}>重新分析内容</button><button className="button" disabled={busy} onClick={()=>void operation("/admin/ai/reindex","索引更新")}>重建知识索引</button><button className="button primary" disabled={busy} onClick={()=>void operation("/admin/ai/evaluations/run","评测")}>运行评测集</button></div>}/>{notice&&<div className="notice" role="status">{notice}</div>}
    <section className="metric-grid"><article><strong>{metrics?.summary.calls??0}</strong><span>24h 调用</span></article><article><strong>{metrics?.summary.avg_latency_ms??0} ms</strong><span>平均延迟</span></article><article><strong>{metrics?.summary.failures??0}</strong><span>失败</span></article><article><strong>{metrics?.summary.estimated_cost??0}</strong><span>估算成本</span></article></section>
    <section className="product-panel rag-observability"><header><div><span className="overline">RAG QUALITY · 24H</span><h2>检索质量与索引完整度</h2></div><span className={`status-badge ${(metrics?.rag.avg_citation_coverage??0)>=0.8?"active":"failed"}`}>{Math.round((metrics?.rag.avg_citation_coverage??0)*100)}% 引用覆盖</span></header><div className="metric-grid"><article><strong>{metrics?.rag.rag_queries??0}</strong><span>研究查询</span></article><article><strong>{metrics?.rag.avg_source_count??0}</strong><span>平均独立信源</span></article><article><strong>{metrics?.rag.p95_latency_ms??0} ms</strong><span>P95 延迟</span></article><article><strong>{metrics?.rag.no_evidence??0}</strong><span>无证据降级</span></article><article><strong>{metrics?.index.indexed_documents??0}</strong><span>已索引文档</span></article><article><strong>{metrics?.index.vectorized_chunks??0}/{metrics?.index.chunks??0}</strong><span>向量化 Chunk</span></article><article><strong>{metrics?.index.indexed_sources??0}</strong><span>索引信源</span></article><article><strong>{metrics?.index.missing_source_time??0}</strong><span>缺失源时间</span></article></div></section>
    <section className="admin-ai-grid">{configs.map((c,index)=><article className="product-panel ai-config-card" key={c.task_type}><header><div><span className="overline">{c.task_type}</span><h2>{c.provider_name}</h2></div><span className={`status-badge ${c.status==="ACTIVE"?"active":""}`}>{c.status}</span></header><label>模型<input value={c.model_name??""} onChange={e=>setConfigs(v=>v.map((x,i)=>i===index?{...x,model_name:e.target.value}:x))}/></label><label>服务地址<input value={c.base_url??""} onChange={e=>setConfigs(v=>v.map((x,i)=>i===index?{...x,base_url:e.target.value}:x))}/></label><label>密钥环境变量<input value={c.credential_ref??""} onChange={e=>setConfigs(v=>v.map((x,i)=>i===index?{...x,credential_ref:e.target.value}:x))}/></label><label>状态<select value={c.status} onChange={e=>setConfigs(v=>v.map((x,i)=>i===index?{...x,status:e.target.value}:x))}><option>DISABLED</option><option>ACTIVE</option></select></label><button className="button primary" disabled={busy} onClick={()=>void save(c)}>保存配置</button></article>)}</section>
    <section className="table-panel"><h2>评测历史</h2><div className="data-table"><div className="data-row head"><span>评测集</span><span>能力</span><span>结果</span><span>证据</span></div>{evaluations.map(e=><div className="data-row" key={e.id}><span><strong>{e.name}</strong><small>{new Date(e.started_at).toLocaleString("zh-CN")}</small></span><span>{e.capability}</span><span className={`status-badge ${e.passed?"active":"failed"}`}>{e.passed?"PASS":"FAIL"}</span><span>{JSON.stringify(e.metrics)}</span></div>)}</div></section>
  </div>;
}
function message(e:unknown){return e instanceof ApiError?e.message:e instanceof Error?e.message:"请求失败";}
