"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { PageHeader } from "@/components/page-header";
import { apiFetch, ApiError } from "@/lib/api";

type Subscription = { id: string; name: string; frequency: string; timezone: string; send_time: string; status: string; next_run_at?: string };
type Citation = { citationNo: number; title: string; sourceName: string; sourceUrl: string; supportScore: number };
type ResearchResult = { sessionId: string; answer: string; answerStatus: string; generationProvider: string; citations: Citation[]; latencyMs: number };
type AgentDefinition = { code: string; name: string; description: string; risk_level: string; status: string };
type AgentRun = { id: string; agent_name: string; objective: string; status: string; risk_level: string; result_data?: unknown; error_message?: string; created_at: string };

export function SubscriptionWorkspace() {
  const [items, setItems] = useState<Subscription[]>([]); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { try { setItems(await apiFetch<Subscription[]>("/subscriptions")); } catch (e) { setNotice(message(e)); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = event.currentTarget; const data = new FormData(form); try { await apiFetch("/subscriptions", { method: "POST", body: JSON.stringify({ name: data.get("name"), frequency: data.get("frequency"), timezone: "Asia/Shanghai", sendTime: data.get("sendTime"), maxItems: Number(data.get("maxItems")) }) }); setNotice("订阅已创建，下一次发送时间已写入任务队列。"); form.reset(); await load(); } catch (e) { setNotice(message(e)); } finally { setBusy(false); } }
  async function action(id: string, operation: "send" | "toggle", current?: string) { setBusy(true); try { if (operation === "send") { const result = await apiFetch<{ status: string; itemCount: number }>(`/subscriptions/${id}/send-now`, { method: "POST" }); setNotice(result.status === "SKIPPED" ? "当前没有通过真实模型审核的公开内容，本次投递已跳过，未发送空简报。" : `已发送 ${result.itemCount} 条内容，可在 Mailpit 或 SMTP 邮箱查看。`); } else { await apiFetch(`/subscriptions/${id}/status`, { method: "PUT", body: JSON.stringify({ status: current === "ACTIVE" ? "PAUSED" : "ACTIVE" }) }); setNotice("订阅状态已更新。"); } await load(); } catch (e) { setNotice(message(e)); } finally { setBusy(false); } }
  return <ProtectedWorkspace title="订阅与邮件"><div className="page-shell"><PageHeader title="订阅与邮件" description="每日或每周接收只包含真实模型审核内容的简报。" />
    <div className="subscription-layout"><section className="product-panel subscription-list"><header><h2>我的订阅</h2><span>{items.length} 个</span></header>{items.length ? items.map(item => <article className="subscription-item" key={item.id}><strong>{item.name}</strong><span>{item.frequency === "DAILY" ? "每日" : "每周"} {String(item.send_time).slice(0, 5)} · {item.timezone}</span><small>{item.status} · 下次 {formatDate(item.next_run_at)}</small><div className="workspace-actions"><button disabled={busy} onClick={() => void action(item.id, "send")}>测试发送</button><button disabled={busy} onClick={() => void action(item.id, "toggle", item.status)}>{item.status === "ACTIVE" ? "暂停" : "启用"}</button></div></article>) : <Empty text="尚无订阅，创建后会由调度器自动投递。" />}</section>
      <form className="product-panel subscription-editor" onSubmit={create}><header><div><span className="overline">NEW SUBSCRIPTION</span><h2>新建邮件订阅</h2></div></header><div className="form-grid"><label className="span-2">名称<input name="name" required defaultValue="每日 AI 精选" /></label><label>频率<select name="frequency"><option value="DAILY">每日</option><option value="WEEKLY">每周一</option></select></label><label>发送时间<input name="sendTime" type="time" defaultValue="09:00" required /></label><label>最多条数<input name="maxItems" type="number" min="1" max="50" defaultValue="12" /></label></div><div className="scope-note">仅发送已由非 Mock 模型完成评分、满足发布阈值且公开可见的内容；邮件含一键退订入口。</div><footer><button className="button primary" disabled={busy}>{busy ? "处理中…" : "创建订阅"}</button></footer></form></div>{notice && <WorkspaceNotice notice={notice} onClose={() => setNotice("")} />}
  </div></ProtectedWorkspace>;
}

export function ResearchWorkspace() {
  const [question, setQuestion] = useState(""); const [result, setResult] = useState<ResearchResult | null>(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  async function ask(event: FormEvent) { event.preventDefault(); if (question.trim().length < 3) return setNotice("请输入至少 3 个字符的研究问题。"); setBusy(true); try { setResult(await apiFetch<ResearchResult>("/research/query", { method: "POST", body: JSON.stringify({ question, filters: {} }) })); } catch (e) { setNotice(message(e)); } finally { setBusy(false); } }
  return <ProtectedWorkspace title="知识库问答"><div className="page-shell research-page"><PageHeader title="知识库问答" description="权限前置检索、证据排序、带来源引用的回答；不会引用无权访问的数据。" action={<button className="button" onClick={() => { setQuestion(""); setResult(null); }}>新建研究</button>} />
    <div className="research-layout"><aside className="product-panel research-scope"><h2>检索规则</h2><div className="scope-note">权限过滤发生在检索 SQL 中；只有真实模型审核过的公开文档或当前用户获授权的数据集可被召回。</div><p>回答必须引用证据；真实生成模型不可用时，系统明确降级为证据摘录，不伪装 AI 结论。</p></aside>
      <main className="product-panel research-chat"><header><span className={`status-badge ${result?.generationProvider && !result.generationProvider.includes("fallback") ? "active" : ""}`}>{result ? result.generationProvider : "READY"}</span><small>{result ? `${result.citations.length} 个引用 · ${result.latencyMs}ms` : "等待问题"}</small></header>{result ? <><div className="answer-block"><h2>研究回答</h2><p className="research-answer">{result.answer}</p><div className="citation-row">{result.citations.map(c => <a href={c.sourceUrl} target="_blank" rel="noreferrer" key={c.citationNo}>[{c.citationNo}] {c.sourceName || c.title}</a>)}</div></div></> : <Empty text="提出问题后，这里会显示真实检索结果与逐条引用。" />}<form className="composer" onSubmit={ask}><textarea value={question} onChange={e => setQuestion(e.target.value)} placeholder="例如：过去 7 天 Agent 产品有哪些值得关注的变化？" /><button disabled={busy} aria-label="发送问题">{busy ? "…" : "→"}</button></form></main>
      <aside className="product-panel evidence-panel"><header><h2>引用证据</h2><span>{result?.citations.length ?? 0}</span></header>{result?.citations.map(c => <article key={c.citationNo}><span>{String(c.citationNo).padStart(2, "0")}</span><h3>{c.title}</h3><p>{c.sourceName} · 支持度 {Math.round(c.supportScore * 100)}%</p></article>) ?? <Empty text="暂无证据" />}</aside></div>{notice && <WorkspaceNotice notice={notice} onClose={() => setNotice("")} />}
  </div></ProtectedWorkspace>;
}

export function AgentWorkspace() {
  const [definitions, setDefinitions] = useState<AgentDefinition[]>([]); const [runs, setRuns] = useState<AgentRun[]>([]); const [objective, setObjective] = useState(""); const [selected, setSelected] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { try { const [defs, history] = await Promise.all([apiFetch<AgentDefinition[]>("/agents/definitions"), apiFetch<AgentRun[]>("/agents/runs")]); setDefinitions(defs); setRuns(history); setSelected(v => v || defs[0]?.code || ""); } catch (e) { setNotice(message(e)); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function start(event: FormEvent) { event.preventDefault(); if (!selected || objective.trim().length < 3) return setNotice("请选择 Agent 并填写明确任务目标。"); setBusy(true); try { await apiFetch("/agents/runs", { method: "POST", body: JSON.stringify({ agentCode: selected, objective }) }); setObjective(""); setNotice("任务已创建；高风险工具会进入审批队列。"); await load(); } catch (e) { setNotice(message(e)); } finally { setBusy(false); } }
  return <ProtectedWorkspace title="Agent 工作台"><div className="page-shell agent-page"><PageHeader title="Agent 工作台" description="所有工具调用都记录参数摘要、执行步骤、风险等级和结果；L2/L3 操作必须审批。" />
    <section className="agent-grid">{definitions.map(item => <button type="button" className={`agent-template ${selected === item.code ? "selected" : ""}`} onClick={() => setSelected(item.code)} key={item.code}><span className="agent-avatar">{item.code.slice(0, 1)}</span><h2>{item.name}</h2><p>{item.description}</p><span className="status-badge">{item.risk_level}</span></button>)}</section>
    <form className="product-panel agent-task-form" onSubmit={start}><label>任务目标<textarea value={objective} onChange={e => setObjective(e.target.value)} placeholder="描述期望结果；Agent 只会使用白名单工具。" /></label><button className="button primary" disabled={busy}>{busy ? "创建中…" : "启动 Agent"}</button></form>
    <section className="product-panel agent-run-table"><header><h2>真实运行记录</h2></header>{runs.length ? runs.map(run => <div className="agent-run-row" key={run.id}><strong>{run.objective}</strong><span>{run.agent_name}</span><span className={`agent-run-status ${run.status === "SUCCEEDED" ? "success" : run.status === "FAILED" ? "danger" : "warning"}`}>{run.status}</span><span>{run.risk_level}</span><span>{formatDate(run.created_at)}</span><span title={run.error_message}>详情已留痕</span></div>) : <Empty text="暂无 Agent 运行记录。" />}</section>{notice && <WorkspaceNotice notice={notice} onClose={() => setNotice("")} />}
  </div></ProtectedWorkspace>;
}

function ProtectedWorkspace({ title, children }: { title: string; children: React.ReactNode }) { const { user, loading } = useAuth(); if (loading) return <div className="page-shell"><Empty text="正在检查会话…" /></div>; if (!user) return <div className="page-shell"><div className="permission-state"><span>需要登录</span><h1>{title}</h1><p>注册普通用户账号后即可使用收藏、订阅、研究与 Agent；管理端另需管理员权限。</p><Link className="button primary" href={`/login?returnTo=${encodeURIComponent(location.pathname)}`}>登录或注册</Link></div></div>; return children; }
function Empty({ text }: { text: string }) { return <div className="workspace-empty">{text}</div>; }
function WorkspaceNotice({ notice, onClose }: { notice: string; onClose: () => void }) { return <div className="agent-toast" role="status"><span>{notice}</span><button aria-label="关闭提示" onClick={onClose}>×</button></div>; }
function message(error: unknown) { return error instanceof ApiError ? error.message : error instanceof Error ? error.message : "请求失败"; }
function formatDate(value?: string) { return value ? new Intl.DateTimeFormat("zh-CN", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "—"; }
