"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { Icon } from "@/components/icons";
import { PageHeader } from "@/components/page-header";
import { apiFetch, ApiError } from "@/lib/api";

type Subscription = { id: string; name: string; frequency: string; timezone: string; send_time: string; status: string; next_run_at?: string };
type Citation = { citationNo: number; title: string; sourceName: string; sourceUrl: string; quote: string; supportScore: number; publishedAt?: string; supportStatus: string; evidenceStance: "SUPPORTS" | "REFUTES" | "UNVERIFIED"; freshnessStatus: "CURRENT" | "OUTDATED" | "UNKNOWN"; claimText: string; assessmentReason: string };
type ResearchDiagnostics = { fusion?: string; timeRangeDays?: number; candidateCount?: number; rerankedCount?: number; contextCount?: number; sourceCount?: number; eventCount?: number; officialCount?: number; citationCoverage?: number; stageTimingsMs?: Record<string, number>; evidenceStanceCounts?: Record<string, number>; conflictDetected?: boolean };
type ResearchResult = { sessionId: string; answer: string; answerStatus: string; generationProvider: string; citations: Citation[]; latencyMs: number; diagnostics: ResearchDiagnostics };
type ResearchSession = { id: string; title: string; status: string; createdAt: string; updatedAt: string; latestQuestion?: string; latestAnswerStatus?: string; queryCount: number };
type ResearchTurn = Omit<ResearchResult, "sessionId"> & { runId: string; question: string; createdAt: string };
type ResearchSessionView = { session: ResearchSession; turns: ResearchTurn[] };
type AgentDefinition = { code: string; name: string; description: string; risk_level: string; status: string };
type AgentRun = { id: string; agent_name: string; objective: string; status: string; risk_level: string; result_data?: unknown; error_message?: string; created_at: string };

export function SubscriptionWorkspace() {
  const [items, setItems] = useState<Subscription[]>([]); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { try { setItems(await apiFetch<Subscription[]>("/subscriptions")); } catch (e) { setNotice(message(e)); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = event.currentTarget; const data = new FormData(form); try { await apiFetch("/subscriptions", { method: "POST", body: JSON.stringify({ name: data.get("name"), frequency: data.get("frequency"), timezone: "Asia/Shanghai", sendTime: data.get("sendTime"), maxItems: Number(data.get("maxItems")) }) }); setNotice("订阅已创建，下一次发送时间已写入任务队列。"); form.reset(); await load(); } catch (e) { setNotice(message(e)); } finally { setBusy(false); } }
  async function action(id: string, operation: "send" | "toggle", current?: string) { setBusy(true); try { if (operation === "send") { const result = await apiFetch<{ status: string; itemCount: number }>(`/subscriptions/${id}/send-now`, { method: "POST" }); setNotice(result.status === "SKIPPED" ? "当前没有通过真实模型审核的公开内容，本次投递已跳过，未发送空简报。" : `已发送 ${result.itemCount} 条内容，可在 Mailpit 或 SMTP 邮箱查看。`); } else { await apiFetch(`/subscriptions/${id}/status`, { method: "PUT", body: JSON.stringify({ status: current === "ACTIVE" ? "PAUSED" : "ACTIVE" }) }); setNotice("订阅状态已更新。"); } await load(); } catch (e) { setNotice(message(e)); } finally { setBusy(false); } }
  return <ProtectedWorkspace title="订阅与邮件"><div className="page-shell"><PageHeader title="订阅与邮件" description="每日或每周接收只包含真实模型审核内容的简报。" />
    <div className="subscription-layout"><section className="product-panel subscription-list"><header><h2>我的订阅</h2><span>{items.length} 个</span></header>{items.length ? items.map(item => <article className="subscription-item" key={item.id}><strong>{item.name}</strong><span>{item.frequency === "DAILY" ? "每日" : "每周"} {String(item.send_time).slice(0, 5)} · {item.timezone}</span><small>{item.status} · 下次 {formatDate(item.next_run_at)}</small><div className="workspace-actions"><button disabled={busy} onClick={() => void action(item.id, "send")}>测试发送</button><button disabled={busy} onClick={() => void action(item.id, "toggle", item.status)}>{item.status === "ACTIVE" ? "暂停" : "启用"}</button></div></article>) : <Empty text="尚无订阅，创建后会由调度器自动投递。" />}</section>
      <form className="product-panel subscription-editor" onSubmit={create}><header><div><span className="overline">NEW SUBSCRIPTION</span><h2>新建邮件订阅</h2></div></header><div className="form-grid"><label className="span-2">名称<input name="name" required defaultValue="每日 AI 精选" /></label><label>频率<select name="frequency"><option value="DAILY">每日</option><option value="WEEKLY">每周一</option></select></label><label>发送时间<input name="sendTime" type="time" defaultValue="09:00" required /></label><label>最多条数<input name="maxItems" type="number" min="1" max="50" defaultValue="12" /></label></div><div className="scope-note">仅发送已由非 Mock 模型完成评分、满足发布阈值且公开可见的内容；邮件含一键退订入口。</div><footer><button className="button primary" disabled={busy}>{busy ? "处理中…" : "创建订阅"}</button></footer></form></div>{notice && <WorkspaceNotice notice={notice} onClose={() => setNotice("")} />}
  </div></ProtectedWorkspace>;
}

export function ResearchWorkspace() {
  const { user } = useAuth();
  const [question, setQuestion] = useState(""); const [submittedQuestion, setSubmittedQuestion] = useState(""); const [timeRange, setTimeRange] = useState("auto"); const [officialOnly, setOfficialOnly] = useState(false); const [result, setResult] = useState<ResearchResult | null>(null); const [busy, setBusy] = useState(false); const [busyStage, setBusyStage] = useState(-1); const [activeCitation, setActiveCitation] = useState<number | null>(null); const [notice, setNotice] = useState(""); const [sessions,setSessions]=useState<ResearchSession[]>([]); const [activeSessionId,setActiveSessionId]=useState<string|null>(null); const [historyBusy,setHistoryBusy]=useState(false);
  const loadSessions=useCallback(async()=>{if(!user)return;try{setSessions(await apiFetch<ResearchSession[]>("/research/sessions"));}catch(e){setNotice(message(e));}},[user]);
  useEffect(()=>{const timer=window.setTimeout(()=>void loadSessions(),0);return()=>window.clearTimeout(timer);},[loadSessions]);
  useEffect(() => { if (!busy) return; const timer=window.setInterval(() => setBusyStage(value => Math.min(value + 1, RAG_STAGES.length - 2)),900); return () => window.clearInterval(timer); }, [busy]);
  async function ask(event: FormEvent) { event.preventDefault(); const normalized=question.trim(); if (normalized.length < 3) return setNotice("请输入至少 3 个字符的研究问题。"); setBusyStage(0); setBusy(true); setNotice(""); setResult(null); setActiveCitation(null); setSubmittedQuestion(normalized); setQuestion(""); try { const response=await apiFetch<ResearchResult>("/research/query", { method: "POST", body: JSON.stringify({ sessionId:activeSessionId,question: normalized, filters: { timeRange, officialOnly } }) }); setResult(response);setActiveSessionId(response.sessionId);await loadSessions(); } catch (e) { setQuestion(normalized);setNotice(message(e)); } finally { setBusy(false); setBusyStage(-1); } }
  async function openSession(sessionId:string){setHistoryBusy(true);setNotice("");try{const view=await apiFetch<ResearchSessionView>(`/research/sessions/${sessionId}`);const turn=view.turns.at(-1);setActiveSessionId(sessionId);setActiveCitation(null);if(turn){setSubmittedQuestion(turn.question);setResult({...turn,sessionId});}else{setSubmittedQuestion("");setResult(null);}}catch(e){setNotice(message(e));}finally{setHistoryBusy(false);}}
  function newResearch(){setQuestion("");setSubmittedQuestion("");setResult(null);setActiveCitation(null);setActiveSessionId(null);}
  const d = result?.diagnostics;
  const stanceCounts=d?.evidenceStanceCounts;
  const focusCitation=(citationNo:number) => { setActiveCitation(citationNo); document.getElementById(`evidence-${citationNo}`)?.scrollIntoView({behavior:"smooth",block:"nearest"}); };
  return <ProtectedWorkspace title="知识库问答"><div className="page-shell research-page"><PageHeader title="知识库问答" description="从真实原文中检索、核验并组织答案，每个事实都能回到证据。" action={<button className="button research-new" onClick={newResearch}>新建研究</button>} />
    <section className={`rag-progress ${busy ? "is-running" : result ? "is-complete" : ""}`} aria-label="RAG 检索进度" aria-busy={busy}><header><div><strong>{busy ? "正在构建证据链" : result ? "本次检索链路" : "可信回答流程"}</strong><span>{busy ? "系统正在完成权限、召回与证据核验" : result ? `${result.latencyMs < 1000 ? result.latencyMs + "ms" : (result.latencyMs/1000).toFixed(1) + "s"} 完成 · ${d?.fusion ?? "RRF + RERANK"}` : "问题提交后可查看每个阶段的真实耗时"}</span></div><span className="rag-progress-state">{busy ? "检索中" : result ? "已核验" : "待开始"}</span></header><ol>{RAG_STAGES.map((stage,index) => { const timing=stageTiming(stage.key,d?.stageTimingsMs); const state=result?"done":busyStage===index?"active":busyStage>index?"done":"pending"; return <li className={state} key={stage.key}><i>{state==="done"?"✓":index+1}</i><div><strong>{stage.label}</strong><span>{timing===null ? state==="active"?"处理中…":"等待" : `${timing}ms`}</span></div></li>; })}</ol></section>
    <div className="research-layout"><aside className="research-scope"><div className="rail-heading"><span>检索范围</span><small>在召回前生效</small></div><label>时间范围<select value={timeRange} onChange={e => setTimeRange(e.target.value)}><option value="auto">从问题自动识别</option><option value="7d">最近 7 天</option><option value="30d">最近 30 天</option><option value="90d">最近 90 天</option><option value="all">不限时间</option></select></label><label className="check-row"><input type="checkbox" checked={officialOnly} onChange={e => setOfficialOnly(e.target.checked)} /><span><strong>只看官方与一手信源</strong><small>过滤媒体与社区观点</small></span></label><div className="scope-note"><Icon name="review" />权限过滤先于召回，生成内容不会替代原始证据。</div><div className="research-prompts"><span>试试这样问</span>{RESEARCH_PROMPTS.map(prompt => <button type="button" key={prompt} onClick={() => setQuestion(prompt)}>{prompt}</button>)}</div><div className="research-history"><div><span>历史研究</span><small>{sessions.length}</small></div>{historyBusy?<p>正在载入…</p>:sessions.length?sessions.map(session=><button type="button" className={activeSessionId===session.id?"active":""} onClick={()=>void openSession(session.id)} key={session.id}><strong>{session.title}</strong><span>{session.queryCount} 轮 · {formatDate(session.updatedAt)}</span></button>):<p>发送问题后，会话会自动保存在这里。</p>}</div></aside>
      <main className={`research-chat ${busy ? "is-loading" : ""}`}>{submittedQuestion && <div className="research-question"><span>你的问题</span><p>{submittedQuestion}</p></div>}<div className="research-content">{busy ? <ResearchLoading stage={RAG_STAGES[Math.max(0,busyStage)]?.label} /> : result ? <><div className="answer-toolbar"><div><span className="answer-status-dot" />已基于 {d?.sourceCount ?? 0} 个独立信源核验</div><span>{result.generationProvider}</span></div>{d?.conflictDetected ? <div className="conflict-banner"><Icon name="review" /><div><strong>检测到同一主张的冲突证据</strong><span>回答已并列呈现支持与反驳来源，不将单一观点写成事实。</span></div></div> : null}<article className="answer-block"><h2>研究回答</h2><AnswerWithCitations text={result.answer} onCitation={focusCitation} /><div className="answer-quality"><span><strong>{stanceCounts?.SUPPORTS ?? 0}</strong> 支持</span><span><strong>{stanceCounts?.REFUTES ?? 0}</strong> 反驳</span><span><strong>{stanceCounts?.UNVERIFIED ?? 0}</strong> 未证实</span><span><strong>{stanceCounts?.OUTDATED ?? 0}</strong> 过期</span><span><strong>{Math.round((d?.citationCoverage ?? 0)*100)}%</strong> 引用覆盖</span></div></article></> : <div className="research-welcome"><span className="welcome-mark"><Icon name="research" /></span><h2>从一个值得核验的问题开始</h2><p>系统会先确认权限和时间范围，再从真实采集原文中召回、重排并生成逐句引用的回答。</p><div>{RESEARCH_PROMPTS.slice(0,2).map(prompt => <button type="button" key={prompt} onClick={() => setQuestion(prompt)}>{prompt}</button>)}</div></div>}</div><form className="composer" onSubmit={ask}><textarea aria-label="研究问题" value={question} onChange={e => setQuestion(e.target.value)} placeholder="提出一个需要查证的问题，例如：过去 7 天 Agent 产品有哪些重要变化？" /><div className="composer-footer"><span>{officialOnly ? "官方与一手信源" : "多来源交叉核验"} · {timeRangeLabel(timeRange)}</span><button disabled={busy} aria-label="发送问题"><span>{busy ? "检索中" : "开始研究"}</span><Icon name="arrow" /></button></div></form></main>
      <aside className="evidence-panel"><header><div><h2>引用证据</h2><p>立场、时效与原文片段独立核验</p></div><span>{result?.citations.length ?? 0}</span></header>{result?.citations.length ? <div className="evidence-list">{result.citations.map((c,index) => { const state=evidencePresentation(c); return <article id={`evidence-${c.citationNo}`} className={`${activeCitation===c.citationNo?"active ":""}evidence-${state.tone}${c.freshnessStatus==="OUTDATED"?" evidence-outdated":""}`} style={{animationDelay:`${index*55}ms`}} key={c.citationNo} onMouseEnter={() => setActiveCitation(c.citationNo)}><div className="evidence-index">{String(c.citationNo).padStart(2,"0")}</div><div><div className="evidence-states"><span className={`evidence-state ${state.tone}`}>{state.label}</span>{c.freshnessStatus==="OUTDATED" ? <span className="evidence-state outdated">过期</span> : null}</div><h3>{c.title}</h3><p>{c.sourceName} · {formatDate(c.publishedAt)}</p><div className="evidence-claim">主张：{c.claimText}</div><blockquote>{c.quote}</blockquote><div className="evidence-reason">判断：{c.assessmentReason}</div><a href={c.sourceUrl} target="_blank" rel="noreferrer">查看原文 <Icon name="external" /></a></div></article>; })}</div> : <div className="evidence-empty"><Icon name="report" /><span>{busy ? "证据将在核验后出现" : "提交问题后，这里会呈现可追溯的原文证据。"}</span></div>}</aside></div>{notice && <WorkspaceNotice notice={notice} onClose={() => setNotice("")} />}
  </div></ProtectedWorkspace>;
}

const RAG_STAGES=[{key:"permission",label:"权限校验"},{key:"understanding",label:"查询理解"},{key:"retrieval",label:"混合召回"},{key:"rerank",label:"重排去重"},{key:"generation",label:"证据生成"},{key:"citations",label:"引用校验"}] as const;
const RESEARCH_PROMPTS=["过去 7 天 Agent 产品有哪些重要变化？","比较官方与媒体对 Gemini 更新的不同观点","近期大模型推理优化有哪些进展？"];
function stageTiming(key:(typeof RAG_STAGES)[number]["key"],timings?:Record<string,number>){if(!timings)return null;const keys={permission:["permissionAndSession"],understanding:["queryUnderstanding"],retrieval:["embedding","hybridRetrieval"],rerank:["rerank","diversification"],generation:["generation"],citations:["citationValidation","citationRepair","persistence"]}[key];return keys.reduce((sum,name)=>sum+(timings[name]??0),0);}
function timeRangeLabel(value:string){return ({auto:"自动识别时间", "7d":"最近 7 天", "30d":"最近 30 天", "90d":"最近 90 天",all:"不限时间"} as Record<string,string>)[value]??"自动识别时间";}
function evidencePresentation(citation:Citation){if(citation.evidenceStance==="REFUTES")return {label:"反驳",tone:"refutes"};if(citation.evidenceStance==="UNVERIFIED")return {label:"未证实",tone:"unverified"};return {label:"支持",tone:"supports"};}
function AnswerWithCitations({text,onCitation}:{text:string;onCitation:(citationNo:number)=>void}){return <div className="research-answer">{text.split(/(\[(?:C)?\d+])/g).map((part,index)=>{const match=part.match(/^\[(?:C)?(\d+)]$/);return match?<button type="button" className="inline-citation" onClick={()=>onCitation(Number(match[1]))} key={`${part}-${index}`}>{part}</button>:<span key={index}>{part}</span>;})}</div>;}
function ResearchLoading({stage}:{stage?:string}){return <div className="research-loading" role="status"><span className="loading-orbit"><i /><i /><i /></span><h2>{stage ?? "准备检索"}</h2><p>正在从有权知识库中构建可追溯证据链，请稍候。</p><div className="loading-lines"><i /><i /><i /></div></div>;}

export function AgentWorkspace() {
  const [definitions, setDefinitions] = useState<AgentDefinition[]>([]); const [runs, setRuns] = useState<AgentRun[]>([]); const [objective, setObjective] = useState(""); const [selected, setSelected] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { try { const [defs, history] = await Promise.all([apiFetch<AgentDefinition[]>("/agents/definitions"), apiFetch<AgentRun[]>("/agents/runs")]); setDefinitions(defs); setRuns(history); setSelected(v => v || defs[0]?.code || ""); } catch (e) { setNotice(message(e)); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  async function start(event: FormEvent) { event.preventDefault(); if (!selected || objective.trim().length < 3) return setNotice("请选择 Agent 并填写明确任务目标。"); setBusy(true); try { await apiFetch("/agents/runs", { method: "POST", body: JSON.stringify({ agentCode: selected, objective }) }); setObjective(""); setNotice("任务已创建；高风险工具会进入审批队列。"); await load(); } catch (e) { setNotice(message(e)); } finally { setBusy(false); } }
  return <ProtectedWorkspace title="Agent 工作台"><div className="page-shell agent-page"><PageHeader title="Agent 工作台" description="所有工具调用都记录参数摘要、执行步骤、风险等级和结果；L2/L3 操作必须审批。" />
    <section className="agent-grid">{definitions.map(item => <button type="button" className={`agent-template ${selected === item.code ? "selected" : ""}`} onClick={() => setSelected(item.code)} key={item.code}><span className="agent-avatar">{item.code.slice(0, 1)}</span><h2>{item.name}</h2><p>{item.description}</p><span className="status-badge">{item.risk_level}</span></button>)}</section>
    <form className="product-panel agent-task-form" onSubmit={start}><label>任务目标<textarea value={objective} onChange={e => setObjective(e.target.value)} placeholder="描述期望结果；Agent 只会使用白名单工具。" /></label><button className="button primary" disabled={busy}>{busy ? "创建中…" : "启动 Agent"}</button></form>
    <section className="product-panel agent-run-table"><header><h2>真实运行记录</h2></header>{runs.length ? runs.map(run => <div className="agent-run-row" key={run.id}><strong>{run.objective}</strong><span>{run.agent_name}</span><span className={`agent-run-status ${run.status === "SUCCEEDED" ? "success" : run.status === "FAILED" ? "danger" : "warning"}`}>{run.status}</span><span>{run.risk_level}</span><span>{formatDate(run.created_at)}</span><span title={run.error_message}>详情已留痕</span></div>) : <Empty text="暂无 Agent 运行记录。" />}</section>{notice && <WorkspaceNotice notice={notice} onClose={() => setNotice("")} />}
  </div></ProtectedWorkspace>;
}

function ProtectedWorkspace({ title, children }: { title: string; children: React.ReactNode }) { const { user, loading } = useAuth(); if (loading) return <div className="page-shell"><Empty text="正在检查会话…" /></div>; if (!user) return <div className="page-shell"><div className="permission-state"><span>需要登录</span><h1>{title}</h1><p>注册普通用户账号后即可使用收藏、订阅、研究与 Agent；管理端另需管理员权限。</p><Link className="button primary" href={`/login?returnTo=${encodeURIComponent(location.pathname)}`}>登录或注册</Link></div></div>; return children; }
function Empty({ text }: { text: string }) { return <div className="workspace-empty">{text}</div>; }
function WorkspaceNotice({ notice, onClose }: { notice: string; onClose: () => void }) { return <div className="agent-toast" role="status"><span>{notice}</span><button aria-label="关闭提示" onClick={onClose}>×</button></div>; }
function message(error: unknown) { return error instanceof ApiError ? error.message : error instanceof Error ? error.message : "请求失败"; }
function formatDate(value?: string) { return value ? new Intl.DateTimeFormat("zh-CN", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "—"; }
