"use client";

import Link from "next/link";
import { FormEvent, ReactNode, useCallback, useEffect, useRef, useState } from "react";
import { useAuth } from "@/components/auth-provider";
import { Icon } from "@/components/icons";
import { PageHeader } from "@/components/page-header";
import { apiFetch, ApiError } from "@/lib/api";

type Subscription = { id: string; name: string; frequency: string; timezone: string; send_time: string; weekday?: number; topic_slugs: string | string[]; source_levels: string | string[]; source_entity_ids: string | string[]; content_types: string | string[]; max_items: number; status: string; next_run_at?: string; last_run_at?: string };
type SubscriptionOptions = { topics: Array<{slug:string;name:string}>; sources: Array<{id:string;name:string;official_level:string}> };
type SubscriptionPreview = { id:string; title:string; summary_zh?:string; source_name:string; canonical_url:string; content_type:string; effective_published_at:string };
type SubscriptionDelivery = { id?:string; status?:string; run_status:string; item_count:number; provider_name?:string; last_error?:string; sent_at?:string; scheduled_at:string };
type Citation = { citationNo: number; title: string; sourceName: string; sourceUrl: string; quote: string; supportScore: number; publishedAt?: string; supportStatus: string; evidenceStance: "SUPPORTS" | "REFUTES" | "UNVERIFIED"; freshnessStatus: "CURRENT" | "OUTDATED" | "UNKNOWN"; claimText: string; assessmentReason: string; entailmentStatus: "ENTAILED" | "PARTIAL" | "UNSUPPORTED" | "NOT_EVALUATED"; entailmentScore: number; provenanceStatus: "VERIFIED" | "LEGACY_MISSING" };
type ResearchDiagnostics = { fusion?: string; timeRangeDays?: number; timeRangeKind?: string; timeRangeLabel?: string; windowStart?: string; windowEnd?: string; queryIntent?: string; candidateCount?: number; rerankedCount?: number; contextCount?: number; sourceCount?: number; eventCount?: number; officialCount?: number; citationCoverage?: number; stageTimingsMs?: Record<string, number>; evidenceStanceCounts?: Record<string, number>; conflictDetected?: boolean };
type ResearchFeedback = { id: string; runId: string; rating: "HELPFUL" | "UNHELPFUL"; issueCategories: string[]; comment?: string; triageStatus: string; createdAt: string; updatedAt: string };
type ResearchResult = { runId: string; sessionId: string; answer: string; answerStatus: string; generationProvider: string; citations: Citation[]; latencyMs: number; diagnostics: ResearchDiagnostics; feedback?: ResearchFeedback | null };
type ResearchSession = { id: string; title: string; status: string; createdAt: string; updatedAt: string; latestQuestion?: string; latestAnswerStatus?: string; queryCount: number };
type ResearchTurn = Omit<ResearchResult, "sessionId"> & { question: string; createdAt: string };
type ResearchSessionView = { session: ResearchSession; turns: ResearchTurn[] };
type AgentDefinition = { code: string; name: string; description: string; risk_level: string; allowed_tools: string | string[]; status: string };
type AgentRun = { id: string; agent_code: string; agent_name: string; objective: string; status: string; risk_level: string; result_data?: unknown; error_message?: string; failure_code?: string; token_usage: number; estimated_cost: number; cost_configured: boolean; attempt_no: number; retry_of_run_id?: string; retryable: boolean; started_at?: string; completed_at?: string; created_at: string };
type AgentStep = { id: string; step_no: number; title: string; status: string; result_summary?: string; started_at?: string; completed_at?: string };
type AgentToolCall = { id: string; tool_code: string; risk_level: string; status: string; result_summary?: string; started_at?: string; completed_at?: string };
type AgentApproval = { id: string; status: string; expires_at: string; decision_note?: string; created_at: string; decided_at?: string };
type AgentRunDetail = AgentRun & { permission_snapshot?: unknown; steps: AgentStep[]; toolCalls: AgentToolCall[]; approvals: AgentApproval[] };

export function SubscriptionWorkspace() {
  const [items, setItems] = useState<Subscription[]>([]); const [options,setOptions]=useState<SubscriptionOptions>({topics:[],sources:[]}); const [selectedId,setSelectedId]=useState<string|null>(null); const [editingId,setEditingId]=useState<string|null>(null); const [preview,setPreview]=useState<SubscriptionPreview[]>([]); const [deliveries,setDeliveries]=useState<SubscriptionDelivery[]>([]); const [deleteConfirm,setDeleteConfirm]=useState<string|null>(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const selected=items.find(item=>item.id===selectedId)??null; const editor=items.find(item=>item.id===editingId)??null;
  const load = useCallback(async () => { try { const [subscriptions,filterOptions]=await Promise.all([apiFetch<Subscription[]>("/subscriptions"),apiFetch<SubscriptionOptions>("/subscriptions/options")]);setItems(subscriptions);setOptions(filterOptions);setSelectedId(current=>current&&subscriptions.some(item=>item.id===current)?current:subscriptions[0]?.id??null); } catch (e) { setNotice(message(e)); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const loadDetail=useCallback(async(id:string)=>{try{const [contents,history]=await Promise.all([apiFetch<SubscriptionPreview[]>(`/subscriptions/${id}/preview`),apiFetch<SubscriptionDelivery[]>(`/subscriptions/${id}/deliveries`)]);setPreview(contents);setDeliveries(history);}catch(e){setNotice(message(e));}},[]);
  useEffect(()=>{if(!selectedId)return;const timer=window.setTimeout(()=>void loadDetail(selectedId),0);return()=>window.clearTimeout(timer);},[loadDetail,selectedId]);
  async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const data=new FormData(event.currentTarget);const body={name:data.get("name"),frequency:data.get("frequency"),timezone:"Asia/Shanghai",sendTime:data.get("sendTime"),weekday:Number(data.get("weekday")??1),maxItems:Number(data.get("maxItems")),topicSlugs:data.getAll("topicSlugs"),sourceLevels:data.getAll("sourceLevels"),sourceEntityIds:data.getAll("sourceEntityIds"),contentTypes:data.getAll("contentTypes")};try{const response=editingId?null:await apiFetch<{id:string}>("/subscriptions",{method:"POST",body:JSON.stringify(body)});if(editingId)await apiFetch(`/subscriptions/${editingId}`,{method:"PUT",body:JSON.stringify(body)});setNotice(editingId?"订阅范围和发送计划已更新。":"订阅已创建并进入调度队列。");setEditingId(null);await load();if(response?.id)setSelectedId(response.id);}catch(e){setNotice(message(e));}finally{setBusy(false);}}
  async function action(id:string,operation:"send"|"toggle"|"delete",current?:string){setBusy(true);try{if(operation==="send"){const result=await apiFetch<{status:string;itemCount:number}>(`/subscriptions/${id}/send-now`,{method:"POST"});setNotice(result.status==="SKIPPED"?"当前筛选范围没有合格内容，本次投递已跳过。":`已投递 ${result.itemCount} 条内容。`);}else if(operation==="delete"){await apiFetch(`/subscriptions/${id}`,{method:"DELETE"});setDeleteConfirm(null);setNotice("订阅及其投递记录已删除。");}else{await apiFetch(`/subscriptions/${id}/status`,{method:"PUT",body:JSON.stringify({status:current==="ACTIVE"?"PAUSED":"ACTIVE"})});setNotice("订阅状态已更新。");}await load();if(operation!=="delete")await loadDetail(id);}catch(e){setNotice(message(e));}finally{setBusy(false);}}
  return <ProtectedWorkspace title="订阅与邮件"><div className="page-shell"><PageHeader title="订阅与邮件" description="按主题与信源定时接收经过真实模型审核的公开内容，并追踪每次投递结果。" />
    <div className="subscription-layout"><section className="product-panel subscription-list"><header><h2>我的订阅</h2><span>{items.length} 个</span></header>{items.length?items.map(item=><article className={`subscription-item ${selectedId===item.id?"selected":""}`} key={item.id} onClick={()=>setSelectedId(item.id)}><div className="subscription-item-title"><strong>{item.name}</strong><span className={`status-badge ${item.status==="ACTIVE"?"active":""}`}>{item.status==="ACTIVE"?"运行中":item.status==="PAUSED"?"已暂停":"已退订"}</span></div><span>{item.frequency==="DAILY"?"每日":`每周${weekdayLabel(item.weekday)}`} {String(item.send_time).slice(0,5)} · 最多 {item.max_items} 条</span><small>上次 {formatDate(item.last_run_at)} · 下次 {formatDate(item.next_run_at)}</small><div className="workspace-actions"><button disabled={busy} onClick={event=>{event.stopPropagation();void action(item.id,"send");}}>立即发送</button><button disabled={busy} onClick={event=>{event.stopPropagation();void action(item.id,"toggle",item.status);}}>{item.status==="ACTIVE"?"暂停":"启用"}</button><button onClick={event=>{event.stopPropagation();setEditingId(item.id);}}>编辑</button>{deleteConfirm===item.id?<button className="danger" disabled={busy} onClick={event=>{event.stopPropagation();void action(item.id,"delete");}}>确认删除</button>:<button onClick={event=>{event.stopPropagation();setDeleteConfirm(item.id);}}>删除</button>}</div></article>):<Empty text="尚无订阅，创建后会由调度器自动投递。" />}</section>
      <div className="subscription-main"><SubscriptionEditor key={editor?.id??"new"} editor={editor} options={options} busy={busy} onSave={save} onCancel={()=>setEditingId(null)} />{selected?<SubscriptionInsight selected={selected} preview={preview} deliveries={deliveries} />:null}</div></div>{notice&&<WorkspaceNotice notice={notice} onClose={()=>setNotice("")} />}
  </div></ProtectedWorkspace>;
}

function SubscriptionEditor({editor,options,busy,onSave,onCancel}:{editor:Subscription|null;options:SubscriptionOptions;busy:boolean;onSave:(event:FormEvent<HTMLFormElement>)=>void;onCancel:()=>void}){
  return <form className="product-panel subscription-editor" onSubmit={onSave}><header><div><span className="overline">{editor?"EDIT SUBSCRIPTION":"NEW SUBSCRIPTION"}</span><h2>{editor?"编辑订阅":"新建邮件订阅"}</h2></div>{editor?<button type="button" className="button" onClick={onCancel}>取消编辑</button>:null}</header><div className="form-grid"><label className="span-2">名称<input name="name" required defaultValue={editor?.name??"每日 AI 精选"} /></label><label>频率<select name="frequency" defaultValue={editor?.frequency??"DAILY"}><option value="DAILY">每日</option><option value="WEEKLY">每周</option></select></label><label>星期<select name="weekday" defaultValue={editor?.weekday??1}>{[1,2,3,4,5,6,7].map(day=><option value={day} key={day}>周{weekdayLabel(day)}</option>)}</select></label><label>发送时间<input name="sendTime" type="time" defaultValue={String(editor?.send_time??"09:00").slice(0,5)} required /></label><label>最多条数<input name="maxItems" type="number" min="1" max="50" defaultValue={editor?.max_items??12} /></label><fieldset className="span-2 subscription-filter-group"><legend>内容类型</legend>{[["ARTICLE","资讯"],["RESEARCH","论文/研究"],["RELEASE","模型发布"],["TUTORIAL","教程实践"],["OTHER","其他"]].map(([value,label])=><label key={value}><input type="checkbox" name="contentTypes" value={value} defaultChecked={asArray(editor?.content_types).includes(value)} />{label}</label>)}</fieldset><label>主题（可多选）<select name="topicSlugs" multiple defaultValue={asArray(editor?.topic_slugs)}>{options.topics.map(topic=><option value={topic.slug} key={topic.slug}>{topic.name}</option>)}</select></label><label>指定信源（可多选）<select name="sourceEntityIds" multiple defaultValue={asArray(editor?.source_entity_ids)}>{options.sources.map(source=><option value={source.id} key={source.id}>{source.name} · {source.official_level}</option>)}</select></label><fieldset className="span-2 subscription-filter-group"><legend>信源等级</legend>{[["OFFICIAL","官方"],["FIRST_PARTY","一手"],["THIRD_PARTY","第三方"]].map(([value,label])=><label key={value}><input type="checkbox" name="sourceLevels" value={value} defaultChecked={!editor||asArray(editor.source_levels).includes(value)} />{label}</label>)}</fieldset></div><div className="scope-note">未选择主题、指定信源或内容类型时表示“不限制”；预览和正式投递共用同一套准入与筛选规则。</div><footer><button className="button primary" disabled={busy}>{busy?"处理中…":editor?"保存修改":"创建订阅"}</button></footer></form>;
}

function SubscriptionInsight({selected,preview,deliveries}:{selected:Subscription;preview:SubscriptionPreview[];deliveries:SubscriptionDelivery[]}){
  return <section className="product-panel subscription-insight"><header><div><span className="overline">DELIVERY PREVIEW</span><h2>{selected.name}</h2></div><span>{preview.length} 条候选</span></header><div className="subscription-insight-grid"><div><h3>发送前预览</h3>{preview.length?preview.slice(0,5).map(item=><a href={item.canonical_url} target="_blank" rel="noreferrer" key={item.id}><strong>{item.title}</strong><span>{item.source_name} · {subscriptionContentTypeLabel(item.content_type)}</span></a>):<Empty text="当前范围没有符合准入条件的内容。" />}</div><div><h3>最近投递</h3>{deliveries.length?deliveries.slice(0,5).map((delivery,index)=><article key={delivery.id??`${delivery.scheduled_at}-${index}`}><strong>{deliveryStatusLabel(delivery.status??delivery.run_status)}</strong><span>{delivery.item_count} 条 · {formatDate(delivery.sent_at??delivery.scheduled_at)}</span>{delivery.last_error?<small>{delivery.last_error}</small>:null}</article>):<Empty text="尚无投递记录。" />}</div></div></section>;
}

function asArray(value?:string|string[]){if(!value)return [];if(Array.isArray(value))return value;try{return JSON.parse(value) as string[];}catch{return [];}}
function weekdayLabel(value?:number){return ["一","二","三","四","五","六","日"][(value??1)-1]??"一";}
function subscriptionContentTypeLabel(value:string){return ({ARTICLE:"资讯",RESEARCH:"论文/研究",RELEASE:"模型发布",TUTORIAL:"教程实践",OTHER:"其他"} as Record<string,string>)[value]??value;}
function deliveryStatusLabel(value:string){return ({SENT:"发送成功",SUCCEEDED:"发送成功",FAILED:"发送失败",SKIPPED:"无内容，已跳过",RUNNING:"发送中",SENDING:"发送中"} as Record<string,string>)[value]??value;}

export function ResearchWorkspace() {
  const { user } = useAuth();
  const [question, setQuestion] = useState(""); const [submittedQuestion, setSubmittedQuestion] = useState(""); const [timeRange, setTimeRange] = useState("auto"); const [officialOnly, setOfficialOnly] = useState(false); const [scopeOpen,setScopeOpen]=useState(false); const [result, setResult] = useState<ResearchResult | null>(null); const [busy, setBusy] = useState(false); const [feedbackBusy,setFeedbackBusy]=useState(false); const [busyStage, setBusyStage] = useState(-1); const [activeCitation, setActiveCitation] = useState<number | null>(null); const [notice, setNotice] = useState(""); const [sessions,setSessions]=useState<ResearchSession[]>([]); const [activeSessionId,setActiveSessionId]=useState<string|null>(null); const [sessionTurns,setSessionTurns]=useState<ResearchTurn[]>([]); const [historyBusy,setHistoryBusy]=useState(false); const conversationRef=useRef<HTMLDivElement>(null);
  const loadSessions=useCallback(async()=>{if(!user)return;try{setSessions(await apiFetch<ResearchSession[]>("/research/sessions"));}catch(e){setNotice(message(e));}},[user]);
  useEffect(()=>{const timer=window.setTimeout(()=>void loadSessions(),0);return()=>window.clearTimeout(timer);},[loadSessions]);
  useEffect(() => { if (!busy) return; const timer=window.setInterval(() => setBusyStage(value => Math.min(value + 1, RAG_STAGES.length - 2)),900); return () => window.clearInterval(timer); }, [busy]);
  async function ask(event: FormEvent) { event.preventDefault(); const normalized=question.trim(); if (normalized.length < 3) return setNotice("请输入至少 3 个字符的研究问题。"); const continuingSession=Boolean(activeSessionId); setBusyStage(0); setBusy(true); setNotice(""); setResult(null); setActiveCitation(null); setSubmittedQuestion(normalized); setQuestion(""); requestAnimationFrame(()=>conversationRef.current?.scrollTo({top:0,behavior:"smooth"})); try { const response=await apiFetch<ResearchResult>("/research/query", { method: "POST", body: JSON.stringify({ sessionId:activeSessionId,question: normalized, filters: { timeRange, officialOnly } }) }); const turn:ResearchTurn={...response,question:normalized,createdAt:new Date().toISOString()};setResult(response);setSessionTurns(current=>continuingSession?[...current,turn]:[turn]);setActiveSessionId(response.sessionId);await loadSessions(); } catch (e) { setQuestion(normalized);setNotice(message(e)); } finally { setBusy(false); setBusyStage(-1); } }
  async function openSession(sessionId:string){setHistoryBusy(true);setNotice("");try{const view=await apiFetch<ResearchSessionView>(`/research/sessions/${sessionId}`);const turn=view.turns.at(-1);setActiveSessionId(sessionId);setSessionTurns(view.turns);setActiveCitation(null);if(turn){setSubmittedQuestion(turn.question);setResult({...turn,sessionId});}else{setSubmittedQuestion("");setResult(null);}requestAnimationFrame(()=>conversationRef.current?.scrollTo({top:0,behavior:"smooth"}));}catch(e){setNotice(message(e));}finally{setHistoryBusy(false);}}
  async function submitFeedback(rating:"HELPFUL"|"UNHELPFUL",issueCategories:string[],comment:string){if(!result)return false;setFeedbackBusy(true);setNotice("");try{const feedback=await apiFetch<ResearchFeedback>(`/research/runs/${result.runId}/feedback`,{method:"POST",body:JSON.stringify({rating,issueCategories,comment})});setResult(current=>current?{...current,feedback}:current);setSessionTurns(current=>current.map(turn=>turn.runId===result.runId?{...turn,feedback}:turn));setNotice(rating==="HELPFUL"?"感谢确认，这条回答会作为正向质量样本。":"问题已记录，管理员可在 RAG 监控中归类为评测候选。");return true;}catch(e){setNotice(message(e));return false;}finally{setFeedbackBusy(false);}}
  function newResearch(){setQuestion("");setSubmittedQuestion("");setResult(null);setActiveCitation(null);setActiveSessionId(null);setSessionTurns([]);}
  function selectTurn(turn:ResearchTurn){if(!activeSessionId)return;setSubmittedQuestion(turn.question);setResult({...turn,sessionId:activeSessionId});setActiveCitation(null);requestAnimationFrame(()=>conversationRef.current?.scrollTo({top:0,behavior:"smooth"}));}
  const d = result?.diagnostics;
  const stanceCounts=d?.evidenceStanceCounts;
  const verification=verificationPresentation(result);
  const focusCitation=(citationNo:number) => { setActiveCitation(citationNo); document.getElementById(`evidence-${citationNo}`)?.scrollIntoView({behavior:"smooth",block:"nearest"}); };
  return <ProtectedWorkspace title="知识库问答"><div className="page-shell research-page"><PageHeader title="知识库问答" description="从真实原文中检索、核验并组织答案，每个事实都能回到证据。" action={<button className="button research-new" onClick={newResearch}>新建研究</button>} />
    <section className={`rag-progress ${busy ? "is-running" : result ? "is-complete" : ""}`} aria-label="RAG 检索进度" aria-busy={busy}><header><div><strong>{busy ? "正在构建证据链" : result ? "本次检索链路" : "可信回答流程"}</strong><span>{busy ? "系统正在完成权限、召回与证据核验" : result ? `${result.latencyMs < 1000 ? result.latencyMs + "ms" : (result.latencyMs/1000).toFixed(1) + "s"} 完成 · ${d?.fusion ?? "RRF + RERANK"}` : "问题提交后可查看每个阶段的真实耗时"}</span></div><span className={`rag-progress-state ${verification.tone}`}>{busy ? "检索中" : result ? verification.label : "待开始"}</span></header><ol>{RAG_STAGES.map((stage,index) => { const timing=stageTiming(stage.key,d?.stageTimingsMs); const state=result?"done":busyStage===index?"active":busyStage>index?"done":"pending"; return <li className={state} key={stage.key}><i>{state==="done"?"✓":index+1}</i><div><strong>{stage.label}</strong><span>{timing===null ? state==="active"?"处理中…":"等待" : `${timing}ms`}</span></div></li>; })}</ol></section>
    <div className="research-layout"><aside className={`research-scope ${scopeOpen?"scope-open":""}`}><button type="button" className="research-scope-toggle" aria-expanded={scopeOpen} onClick={()=>setScopeOpen(value=>!value)}><span><strong>检索范围</strong><small>{timeRangeLabel(timeRange)} · {officialOnly?"官方/一手":"全部可信来源"}</small></span><i>{scopeOpen?"收起":"调整"}</i></button>{scopeOpen?<div className="research-scope-controls"><label>时间范围<select value={timeRange} onChange={e => setTimeRange(e.target.value)}><option value="auto">从问题自动识别</option><option value="7d">最近 7 天</option><option value="30d">最近 30 天</option><option value="90d">最近 90 天</option><option value="all">不限时间</option></select></label><label className="check-row"><input type="checkbox" checked={officialOnly} onChange={e => setOfficialOnly(e.target.checked)} /><span><strong>只看官方与一手信源</strong><small>过滤媒体与社区观点</small></span></label><div className="scope-note"><Icon name="review" />权限过滤先于召回，生成内容不会替代原始证据。</div></div>:null}<div className="research-history"><div className="research-history-heading"><span>历史对话</span><small>{sessions.length} 个真实会话</small></div>{historyBusy?<p>正在从数据库载入…</p>:sessions.length?sessions.map(session=><div className="research-history-session" key={session.id}><button type="button" className={activeSessionId===session.id?"active":""} onClick={()=>void openSession(session.id)}><strong>{session.latestQuestion||session.title}</strong><span>{session.queryCount} 轮真实对话 · {formatDate(session.updatedAt)}</span>{session.latestQuestion&&session.latestQuestion!==session.title?<small>{session.title}</small>:null}</button>{activeSessionId===session.id&&sessionTurns.length?<div className="research-history-turns" aria-label="当前会话的真实历史轮次">{sessionTurns.map((turn,index)=><button type="button" className={result?.runId===turn.runId?"active":""} onClick={()=>selectTurn(turn)} key={turn.runId}><i>{index+1}</i><span>{turn.question}</span><small>{formatDate(turn.createdAt)}</small></button>)}</div>:null}</div>):<p>发送问题后，真实会话会自动保存在数据库并显示在这里。</p>}</div></aside>
      <main className={`research-chat ${busy ? "is-loading" : ""}`}>
        <div className="research-chat-scroll" ref={conversationRef}>
          {sessionTurns.length>1?<nav className="research-turns" aria-label="当前研究对话历史"><span>本研究共 {sessionTurns.length} 轮</span><div>{sessionTurns.map((turn,index)=><button type="button" className={result?.runId===turn.runId?"active":""} onClick={()=>selectTurn(turn)} key={turn.runId}><strong>{index+1}</strong><span>{turn.question}</span></button>)}</div></nav>:null}
          {submittedQuestion && <div className="research-question"><span>你的问题</span><p>{submittedQuestion}</p></div>}
          <div className="research-content">{busy ? <ResearchLoading stage={RAG_STAGES[Math.max(0,busyStage)]?.label} /> : result ? <><div className={`answer-toolbar ${verification.tone}`}><div><span className="answer-status-dot" />{verification.detail}</div><span>{result.generationProvider}</span></div><div className="answer-scope"><span><strong>时间范围</strong>{d?.timeRangeLabel??"未限定"}</span><span><strong>检索证据</strong>{d?.contextCount??0} 条 · {d?.sourceCount??0} 个独立信源</span></div>{d?.conflictDetected ? <div className="conflict-banner"><Icon name="review" /><div><strong>检测到同一主张的冲突证据</strong><span>回答已并列呈现支持与反驳来源，不将单一观点写成事实。</span></div></div> : null}{verification.tone==="limited"?<div className="evidence-limit-banner"><Icon name="review" /><div><strong>当前证据不足以完成交叉验证</strong><span>请将涉及单一信源或未证实证据的内容作为线索，而不是确定事实。</span></div></div>:null}<article className="answer-block"><header><span>ANSWER</span><h2>研究回答</h2></header><AnswerWithCitations text={result.answer} onCitation={focusCitation} /><div className="answer-quality"><span><strong>{stanceCounts?.SUPPORTS ?? 0}</strong> 支持</span><span><strong>{stanceCounts?.REFUTES ?? 0}</strong> 反驳</span><span><strong>{stanceCounts?.UNVERIFIED ?? 0}</strong> 未证实</span><span><strong>{stanceCounts?.OUTDATED ?? 0}</strong> 过期</span><span><strong>{Math.round((d?.citationCoverage ?? 0)*100)}%</strong> 引用覆盖</span></div><AnswerFeedback key={result.runId} feedback={result.feedback} busy={feedbackBusy} onSubmit={submitFeedback} /></article></> : <div className="research-welcome"><span className="welcome-mark"><Icon name="research" /></span><h2>从一个值得核验的问题开始</h2><p>系统会先确认权限和时间范围，再从真实采集原文中召回、重排并生成逐句引用的回答。</p></div>}</div>
        </div>
        <form className="composer" onSubmit={ask}><textarea aria-label="研究问题" value={question} onChange={e => setQuestion(e.target.value)} placeholder="继续追问，或提出一个需要查证的新问题…" /><div className="composer-footer"><span>{activeSessionId?"继续当前真实会话":"新建真实会话"} · {officialOnly ? "官方与一手信源" : "多来源交叉核验"} · {timeRangeLabel(timeRange)}</span><button disabled={busy} aria-label="发送问题"><span>{busy ? "检索中" : "开始研究"}</span><Icon name="arrow" /></button></div></form>
      </main>
      <aside className="evidence-panel"><header><div><h2>引用证据</h2><p>立场、时效与原文片段独立核验</p></div><span>{result?.citations.length ?? 0}</span></header>{result?.citations.length ? <div className="evidence-list">{result.citations.map((c,index) => { const state=evidencePresentation(c); return <article id={`evidence-${c.citationNo}`} className={`${activeCitation===c.citationNo?"active ":""}evidence-${state.tone}${c.freshnessStatus==="OUTDATED"?" evidence-outdated":""}`} style={{animationDelay:`${index*55}ms`}} key={c.citationNo} onMouseEnter={() => setActiveCitation(c.citationNo)}><div className="evidence-index">{String(c.citationNo).padStart(2,"0")}</div><div><div className="evidence-states"><span className={`evidence-state ${state.tone}`}>{state.label}</span>{c.provenanceStatus==="VERIFIED" ? <span className="evidence-state provenance">来源快照已核验</span> : <span className="evidence-state provenance missing">历史来源不可追溯</span>}{c.entailmentStatus!=="NOT_EVALUATED" ? <span className={`evidence-state entailment ${c.entailmentStatus.toLowerCase()}`}>{entailmentLabel(c)} · {Math.round(c.entailmentScore*100)}%</span> : null}{c.freshnessStatus==="OUTDATED" ? <span className="evidence-state outdated">过期</span> : null}</div><h3>{c.title}</h3><p>{c.sourceName} · {formatDate(c.publishedAt)}</p><div className="evidence-claim">主张：{c.claimText}</div><blockquote>{c.quote}</blockquote><div className="evidence-reason">判断：{c.assessmentReason}</div>{c.provenanceStatus==="VERIFIED"&&c.sourceUrl ? <a href={c.sourceUrl} target="_blank" rel="noreferrer">查看原文 <Icon name="external" /></a> : <span className="evidence-source-missing">原始来源已随旧索引清理，系统不会猜测或伪造链接。</span>}</div></article>; })}</div> : <div className="evidence-empty"><Icon name="report" /><span>{busy ? "证据将在核验后出现" : "提交问题后，这里会呈现可追溯的原文证据。"}</span></div>}</aside></div>{notice && <WorkspaceNotice notice={notice} onClose={() => setNotice("")} />}
  </div></ProtectedWorkspace>;
}

const RAG_STAGES=[{key:"permission",label:"权限校验"},{key:"understanding",label:"查询理解"},{key:"retrieval",label:"混合召回"},{key:"rerank",label:"重排去重"},{key:"generation",label:"证据生成"},{key:"citations",label:"引用校验"}] as const;
function stageTiming(key:(typeof RAG_STAGES)[number]["key"],timings?:Record<string,number>){if(!timings)return null;const keys={permission:["permissionAndSession"],understanding:["queryUnderstanding"],retrieval:["embedding","hybridRetrieval"],rerank:["rerank","diversification"],generation:["generation"],citations:["citationValidation","citationRepair","persistence"]}[key];return keys.reduce((sum,name)=>sum+(timings[name]??0),0);}
function timeRangeLabel(value:string){return ({auto:"自动识别时间", "7d":"最近 7 天", "30d":"最近 30 天", "90d":"最近 90 天",all:"不限时间"} as Record<string,string>)[value]??"自动识别时间";}
function verificationPresentation(result:ResearchResult|null){
  if(!result)return {label:"待开始",detail:"尚未开始证据核验",tone:"pending"};
  if(result.answerStatus==="NO_EVIDENCE")return {label:"无足够证据",detail:"当前范围内没有足够证据回答",tone:"no-evidence"};
  const diagnostics=result.diagnostics;const stances=diagnostics.evidenceStanceCounts??{};const sourceCount=diagnostics.sourceCount??0;const coverage=diagnostics.citationCoverage??0;
  const limited=sourceCount<2||(stances.UNVERIFIED??0)>0||(stances.OUTDATED??0)>0||coverage<.8;
  return limited
    ?{label:"证据有限",detail:`基于 ${sourceCount} 个独立信源，部分结论仍需复核`,tone:"limited"}
    :{label:"已交叉核验",detail:`已基于 ${sourceCount} 个独立信源完成交叉核验`,tone:"verified"};
}
function evidencePresentation(citation:Citation){if(citation.evidenceStance==="REFUTES")return {label:"反驳",tone:"refutes"};if(citation.evidenceStance==="UNVERIFIED")return {label:"未证实",tone:"unverified"};return {label:"支持",tone:"supports"};}
function entailmentLabel(citation:Citation){if(citation.entailmentStatus==="ENTAILED")return "原文匹配";if(citation.entailmentStatus==="PARTIAL")return "部分匹配";return "匹配不足";}
type AnswerBlock =
  | { kind:"heading"; text:string; level:number }
  | { kind:"paragraph"; text:string }
  | { kind:"bullets"; items:string[] }
  | { kind:"numbers"; items:string[] };

function AnswerWithCitations({text,onCitation}:{text:string;onCitation:(citationNo:number)=>void}){
  const blocks=parseAnswerBlocks(text);
  let paragraphIndex=0;
  return <div className="research-answer">{blocks.map((block,index)=>{
    if(block.kind==="heading"){const Heading=block.level<=2?"h3":"h4";return <Heading key={index}>{renderAnswerInline(block.text,onCitation)}</Heading>;}
    if(block.kind==="bullets")return <ul key={index}>{block.items.map((item,itemIndex)=><li key={itemIndex}>{renderAnswerInline(item,onCitation)}</li>)}</ul>;
    if(block.kind==="numbers")return <ol key={index}>{block.items.map((item,itemIndex)=><li key={itemIndex}>{renderAnswerInline(item,onCitation)}</li>)}</ol>;
    const lead=paragraphIndex++===0;
    return <p className={lead?"answer-lead":undefined} key={index}>{renderAnswerInline(block.text,onCitation)}</p>;
  })}</div>;
}

function parseAnswerBlocks(text:string):AnswerBlock[]{
  const blocks:AnswerBlock[]=[];
  let listKind:"bullets"|"numbers"|null=null;
  let listItems:string[]=[];
  const flushList=()=>{if(listKind&&listItems.length)blocks.push({kind:listKind,items:listItems});listKind=null;listItems=[];};
  for(const rawLine of text.replace(/\r/g,"").split("\n")){
    const line=rawLine.trim();
    if(!line){flushList();continue;}
    const heading=line.match(/^(#{1,4})\s+(.+)$/);
    if(heading){flushList();blocks.push({kind:"heading",level:heading[1].length,text:heading[2]});continue;}
    const bullet=line.match(/^[-*•]\s+(.+)$/);
    if(bullet){if(listKind!=="bullets"){flushList();listKind="bullets";}listItems.push(bullet[1]);continue;}
    const numbered=line.match(/^\d+[.)、]\s*(.+)$/);
    if(numbered){if(listKind!=="numbers"){flushList();listKind="numbers";}listItems.push(numbered[1]);continue;}
    flushList();
    blocks.push({kind:"paragraph",text:line});
  }
  flushList();
  return blocks.length?blocks:[{kind:"paragraph",text}];
}

function renderAnswerInline(value:string,onCitation:(citationNo:number)=>void):ReactNode[]{
  const normalized=value.replace(/\s+#{2,4}\s+/g," — ");
  return normalized.split(/(\[(?:C)?\d+]|`[^`]+`|\*\*[^*]+\*\*|\[[^\]]+]\(https?:\/\/[^)]+\))/g).filter(Boolean).map((part,index)=>{
    const citation=part.match(/^\[(?:C)?(\d+)]$/);
    if(citation)return <button type="button" className="inline-citation" onClick={()=>onCitation(Number(citation[1]))} key={`${part}-${index}`}>{part}</button>;
    const strong=part.match(/^\*\*(.+)\*\*$/);
    if(strong)return <strong key={index}>{strong[1]}</strong>;
    const code=part.match(/^`(.+)`$/);
    if(code)return <code key={index}>{code[1]}</code>;
    const link=part.match(/^\[([^\]]+)]\((https?:\/\/[^)]+)\)$/);
    if(link)return <a href={link[2]} target="_blank" rel="noreferrer" key={index}>{link[1]}</a>;
    return <span key={index}>{part}</span>;
  });
}
const FEEDBACK_REASONS=[["IRRELEVANT","答非所问"],["MISSING_EVIDENCE","证据不足"],["OUTDATED","信息过时"],["INCORRECT","事实错误"],["INCOMPLETE","回答不完整"],["CITATION_MISMATCH","引用不匹配"],["TOO_VERBOSE","过于冗长"],["OTHER","其他"]] as const;
function AnswerFeedback({feedback,busy,onSubmit}:{feedback?:ResearchFeedback|null;busy:boolean;onSubmit:(rating:"HELPFUL"|"UNHELPFUL",categories:string[],comment:string)=>Promise<boolean>}){
  const [editing,setEditing]=useState(!feedback);const [negativeOpen,setNegativeOpen]=useState(feedback?.rating==="UNHELPFUL");const [categories,setCategories]=useState<string[]>(feedback?.issueCategories??[]);const [comment,setComment]=useState(feedback?.comment??"");
  function toggle(category:string){setCategories(values=>values.includes(category)?values.filter(value=>value!==category):[...values,category]);}
  if(feedback&&!editing)return <div className={`answer-feedback saved ${feedback.rating.toLowerCase()}`}><div><strong>{feedback.rating==="HELPFUL"?"已标记为有帮助":"已提交改进反馈"}</strong><span>{feedback.rating==="UNHELPFUL"?`${feedback.issueCategories.map(reasonLabel).join("、")} · ${triageLabel(feedback.triageStatus)}`:"感谢你的评价"}</span></div><button type="button" onClick={()=>setEditing(true)}>修改评价</button></div>;
  return <div className="answer-feedback"><div className="feedback-prompt"><div><strong>这条回答有帮助吗？</strong><span>你的评价会进入真实 RAG 质量样本。</span></div><div><button type="button" className={feedback?.rating==="HELPFUL"?"active":""} disabled={busy} onClick={()=>void onSubmit("HELPFUL",[],"").then(saved=>saved&&setEditing(false))}>有帮助</button><button type="button" className={negativeOpen?"active negative":""} disabled={busy} onClick={()=>setNegativeOpen(true)}>需要改进</button></div></div>{negativeOpen?<div className="feedback-detail"><div className="feedback-reasons">{FEEDBACK_REASONS.map(([value,label])=><button type="button" className={categories.includes(value)?"selected":""} onClick={()=>toggle(value)} key={value}>{label}</button>)}</div><textarea value={comment} maxLength={1000} onChange={event=>setComment(event.target.value)} placeholder="可选：具体说明哪里不满意，便于复现和优化。" /><div><span>{categories.length?"已选择 "+categories.length+" 项":"至少选择一个原因"}</span><button type="button" disabled={busy||!categories.length} onClick={()=>void onSubmit("UNHELPFUL",categories,comment).then(saved=>saved&&setEditing(false))}>{busy?"提交中…":"提交反馈"}</button></div></div>:null}</div>;
}
function reasonLabel(value:string){return Object.fromEntries(FEEDBACK_REASONS)[value]??value;}
function triageLabel(value:string){return ({NEW:"待分析",TRIAGED:"已归类",EVAL_CANDIDATE:"评测候选",RESOLVED:"已解决",DISMISSED:"已忽略"} as Record<string,string>)[value]??value;}
function ResearchLoading({stage}:{stage?:string}){return <div className="research-loading" role="status"><span className="loading-orbit"><i /><i /><i /></span><h2>{stage ?? "准备检索"}</h2><p>正在从有权知识库中构建可追溯证据链，请稍候。</p><div className="loading-lines"><i /><i /><i /></div></div>;}

export function AgentWorkspace() {
  const [definitions, setDefinitions] = useState<AgentDefinition[]>([]); const [runs, setRuns] = useState<AgentRun[]>([]); const [objective, setObjective] = useState(""); const [selected, setSelected] = useState(""); const [selectedRunId,setSelectedRunId]=useState<string|null>(null); const [detail,setDetail]=useState<AgentRunDetail|null>(null); const [busy, setBusy] = useState(false); const [detailBusy,setDetailBusy]=useState(false); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { try { const [defs, history] = await Promise.all([apiFetch<AgentDefinition[]>("/agents/definitions"), apiFetch<AgentRun[]>("/agents/runs")]); setDefinitions(defs); setRuns(history); setSelected(v => v || defs[0]?.code || ""); } catch (e) { setNotice(message(e)); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => void load(), 0); return () => window.clearTimeout(timer); }, [load]);
  const hasActiveRuns=runs.some(run=>["QUEUED","WAITING_APPROVAL","RUNNING"].includes(run.status));
  useEffect(()=>{if(!hasActiveRuns)return;const timer=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(timer);},[hasActiveRuns,load]);
  const loadDetail=useCallback(async(id:string)=>{setDetailBusy(true);try{setDetail(await apiFetch<AgentRunDetail>(`/agents/runs/${id}`));setSelectedRunId(id);}catch(e){setNotice(message(e));}finally{setDetailBusy(false);}},[]);
  useEffect(()=>{if(!selectedRunId||!hasActiveRuns)return;const timer=window.setInterval(()=>void loadDetail(selectedRunId),5000);return()=>window.clearInterval(timer);},[hasActiveRuns,loadDetail,selectedRunId]);
  async function start(event: FormEvent) { event.preventDefault(); if (!selected || objective.trim().length < 3) return setNotice("请选择 Agent 并填写明确任务目标。"); setBusy(true); try { await apiFetch("/agents/runs", { method: "POST", body: JSON.stringify({ agentCode: selected, objective }) }); setObjective(""); setNotice("任务已创建；高风险工具会进入审批队列。"); await load(); } catch (e) { setNotice(message(e)); } finally { setBusy(false); } }
  async function lifecycle(run:AgentRun,action:"cancel"|"retry"){setBusy(true);try{if(action==="cancel"){await apiFetch(`/agents/runs/${run.id}/cancel`,{method:"POST"});setNotice("取消请求已生效，未开始的步骤和审批已终止。");await Promise.all([load(),loadDetail(run.id)]);}else{const created=await apiFetch<{id:string}>(`/agents/runs/${run.id}/retry`,{method:"POST"});setNotice("已从不可变原始输入创建新的安全重试。");await load();await loadDetail(created.id);}}catch(e){setNotice(message(e));}finally{setBusy(false);}}
  const selectedDefinition=definitions.find(item=>item.code===selected);const guide=agentGuide(selected);
  return <ProtectedWorkspace title="Agent 工作台"><div className="page-shell agent-page"><PageHeader title="Agent 工作台" description="选择任务模板，确认工具、数据范围与审批要求，再启动可审计的 Agent 运行。" />
    <section className="agent-grid">{definitions.map(item => <button type="button" className={`agent-template ${selected === item.code ? "selected" : ""}`} onClick={() => {setSelected(item.code);setObjective("");}} key={item.code}><div className="agent-template-heading"><span className="agent-avatar">{item.code.slice(0, 1)}</span><span className="status-badge">{item.risk_level}</span></div><h2>{item.name}</h2><p>{item.description}</p><strong className="agent-template-cta">{selected===item.code?"已选择 · 配置任务":"选择此任务 →"}</strong></button>)}</section>
    <form className="product-panel agent-task-form" onSubmit={start}><header><div><span className="overline">TASK BUILDER</span><h2>{selectedDefinition?.name??"选择 Agent"}</h2><p>先选择一个常见任务，也可以直接编写自己的明确目标。</p></div><span className={`agent-risk-badge risk-${selectedDefinition?.risk_level.toLowerCase()}`}>{selectedDefinition?.risk_level??"—"} · {guide.approval}</span></header><div className="agent-task-builder"><section><h3>1. 选择任务模板</h3><div className="agent-preset-list">{guide.presets.map(preset=><button type="button" className={objective===preset.objective?"active":""} onClick={()=>setObjective(preset.objective)} key={preset.label}><strong>{preset.label}</strong><span>{preset.description}</span></button>)}</div></section><section><h3>2. 明确预期结果</h3><label>任务目标<textarea value={objective} maxLength={1000} onChange={e => setObjective(e.target.value)} placeholder={guide.placeholder} /></label><small>{objective.length}/1000 · 任务目标会作为不可变输入写入审计记录</small></section><aside><h3>3. 执行前确认</h3><dl><div><dt>允许工具</dt><dd>{asArray(selectedDefinition?.allowed_tools).map(tool=><span key={tool}>{toolLabel(tool)}</span>)}</dd></div><div><dt>数据范围</dt><dd>{guide.scope}</dd></div><div><dt>风险与审批</dt><dd>{guide.risk}</dd></div><div><dt>预期产物</dt><dd>{guide.output}</dd></div></dl></aside></div><footer><span>运行后可在下方查看步骤时间线、工具结果、审批状态和失败恢复建议。</span><button className="button primary" disabled={busy||objective.trim().length<3}>{busy ? "创建中…" : "确认并启动 Agent"}</button></footer></form>
    <section className="product-panel agent-run-table"><header><div><h2>真实运行记录</h2><p>运行中任务每 5 秒刷新；失败重试始终创建新运行，不覆盖原审计。</p></div><span>{runs.length} 条</span></header><div className="agent-run-head"><span>目标</span><span>Agent</span><span>状态</span><span>尝试</span><span>创建时间</span><span>详情</span></div>{runs.length ? runs.map(run => <div className={`agent-run-row ${selectedRunId===run.id?"selected":""}`} key={run.id}><strong title={run.objective}>{run.objective}</strong><span>{run.agent_name}</span><span className={`agent-run-status ${run.status === "SUCCEEDED" ? "success" : run.status === "FAILED"||run.status==="CANCELLED" ? "danger" : "warning"}`}>{agentStatusLabel(run.status)}</span><span>{run.attempt_no}/{3}</span><span>{formatDate(run.created_at)}</span><button type="button" className="agent-run-open" aria-label={`查看 ${run.objective} 详情`} onClick={()=>void loadDetail(run.id)}><Icon name="arrow" /></button></div>) : <Empty text="暂无 Agent 运行记录。" />}</section>
    {selectedRunId?<section className="product-panel agent-run-detail" aria-live="polite">{detailBusy&&!detail?<p className="workspace-empty">正在加载运行审计…</p>:detail?<><header><div><span className="overline">RUN AUDIT · ATTEMPT {detail.attempt_no}</span><h2>{detail.objective}</h2><p>{detail.agent_name} · {detail.risk_level} · 创建于 {formatDate(detail.created_at)}</p></div><div className="agent-detail-actions">{["QUEUED","WAITING_APPROVAL","RUNNING"].includes(detail.status)?<button className="button" disabled={busy} onClick={()=>void lifecycle(detail,"cancel")}>取消运行</button>:null}{detail.retryable?<button className="button primary" disabled={busy} onClick={()=>void lifecycle(detail,"retry")}>安全重试</button>:null}<button className="icon-button" aria-label="关闭运行详情" onClick={()=>{setSelectedRunId(null);setDetail(null);}}>×</button></div></header><div className="agent-run-summary"><article><span>运行状态</span><strong>{agentStatusLabel(detail.status)}</strong><small>{detail.failure_code?agentFailureLabel(detail.failure_code):"状态机正常"}</small></article><article><span>模型用量</span><strong>{formatAgentNumber(detail.token_usage??0)} tokens</strong><small>估算成本 {detail.cost_configured?Number(detail.estimated_cost??0).toFixed(6):"待配置"}</small></article><article><span>执行时间</span><strong>{agentDuration(detail)}</strong><small>{detail.completed_at?"已结束":"等待完成"}</small></article></div>{detail.error_message?<div className="notice error">{detail.error_message}</div>:null}<div className="agent-audit-grid"><div><h3>执行步骤</h3>{detail.steps.map(step=><article className="agent-audit-row" key={step.id}><span className={`status-badge ${step.status==="SUCCEEDED"?"active":step.status==="FAILED"?"failed":""}`}>{agentStatusLabel(step.status)}</span><div><strong>{step.step_no}. {step.title}</strong><p>{step.result_summary??"等待执行"}</p></div><small>{formatDate(step.completed_at??step.started_at)}</small></article>)}</div><div><h3>工具与审批</h3>{detail.toolCalls.map(call=><article className="agent-audit-row" key={call.id}><span className={`status-badge ${call.status==="SUCCEEDED"?"active":call.status==="FAILED"||call.status==="DENIED"?"failed":""}`}>{agentStatusLabel(call.status)}</span><div><strong>{call.tool_code} · {call.risk_level}</strong><p>{call.result_summary??"参数 Hash 已留存，原始敏感参数不展示。"}</p></div><small>{formatDate(call.completed_at??call.started_at)}</small></article>)}{detail.approvals.map(approval=><article className="agent-audit-row approval" key={approval.id}><span className={`status-badge ${approval.status==="APPROVED"?"active":approval.status==="REJECTED"||approval.status==="EXPIRED"?"failed":""}`}>{agentStatusLabel(approval.status)}</span><div><strong>人工审批</strong><p>{approval.decision_note??`有效期至 ${formatDate(approval.expires_at)}`}</p></div><small>{formatDate(approval.decided_at??approval.created_at)}</small></article>)}</div></div></>:null}</section>:null}{notice && <WorkspaceNotice notice={notice} onClose={() => setNotice("")} />}
  </div></ProtectedWorkspace>;
}

/*
const AGENT_GUIDES:Record<string,{approval:string;scope:string;risk:string;output:string;placeholder:string;presets:Array<{label:string;description:string;objective:string}>}>={
  RESEARCH:{approval:"无需审批",scope:"当前用户可访问的公开知识库",risk:"只读检索，不执行写操作",output:"带引用的研究摘要",placeholder:"例如：总结过去 7 天 Agent 产品变化，按公司分组并列出来源。",presets:[{label:"近期动态研究",description:"按时间范围总结已核验变化",objective:"总结过去 7 天当前有权知识库中的 Agent 产品重要变化，按公司分组并保留原始来源。"},{label:"专题对比",description:"比较多个来源的相同与不同观点",objective:"比较官方与媒体对近期大模型更新的观点，区分已证实事实、观点与待核验信息。"}]},
  SUBSCRIPTION:{approval:"登录用户自有数据",scope:"仅创建当前用户自己的订阅",risk:"L1 写操作；结果可在订阅页暂停或删除",output:"一条可管理的邮件订阅",placeholder:"例如：每天 09:00 创建一份 AI 精选订阅。",presets:[{label:"每日精选",description:"创建每天早间简报",objective:"创建一条每天 09:00 发送的 AI 精选订阅。"},{label:"每周研究摘要",description:"创建每周汇总订阅",objective:"创建一条每周一 09:00 发送的 AI 研究摘要订阅。"}]},
  SOURCE_OPS:{approval:"需要管理员审批",scope:"公开信源健康与 Endpoint 配置",risk:"L2；探测操作必须审批，参数摘要留痕",output:"健康诊断与配置建议",placeholder:"例如：检查失败信源并给出不修改配置的修复建议。",presets:[{label:"信源健康检查",description:"诊断失败和低质量信源",objective:"检查当前公开信源健康状态，列出失败 Endpoint、可能原因和修复建议，不直接修改配置。"},{label:"来源质量审计",description:"识别单一来源占比与质量风险",objective:"审计当前信源质量与多样性，列出低质量、重复率高和单一来源占比风险。"}]},
  CRAWL_OPS:{approval:"需要管理员审批",scope:"采集任务、队列、重试与死信",risk:"L2；重试采集必须审批且可取消",output:"队列诊断与安全重试建议",placeholder:"例如：诊断采集积压和失败任务，但先不要执行重试。",presets:[{label:"采集队列诊断",description:"只读检查积压与失败",objective:"诊断当前采集队列积压、失败任务和死信情况，给出处理优先级，不执行重试。"},{"label":"失败任务恢复",description":"定位可安全重试的任务",objective":"识别最近失败且可安全重试的采集任务，说明风险并在审批后执行重试。"}]}
};
*/
const AGENT_GUIDES:Record<string,{approval:string;scope:string;risk:string;output:string;placeholder:string;presets:Array<{label:string;description:string;objective:string}>}>={
  RESEARCH:{approval:"无需审批",scope:"当前用户可访问的公开知识库",risk:"只读检索，不执行写操作",output:"带引用的研究摘要",placeholder:"例如：总结过去 7 天 Agent 产品变化，按公司分组并列出来源。",presets:[
    {label:"近期动态研究",description:"按时间范围总结已核验变化",objective:"总结过去 7 天当前有权知识库中的 Agent 产品重要变化，按公司分组并保留原始来源。"},
    {label:"专题对比",description:"比较多个来源的相同与不同观点",objective:"比较官方与媒体对近期大模型更新的观点，区分已证实事实、观点与待核验信息。"}]},
  SUBSCRIPTION:{approval:"登录用户自有数据",scope:"仅创建当前用户自己的订阅",risk:"L1 写操作；结果可在订阅页暂停或删除",output:"一条可管理的邮件订阅",placeholder:"例如：每天 09:00 创建一份 AI 精选订阅。",presets:[
    {label:"每日精选",description:"创建每天早间简报",objective:"创建一条每天 09:00 发送的 AI 精选订阅。"},
    {label:"每周研究摘要",description:"创建每周汇总订阅",objective:"创建一条每周一 09:00 发送的 AI 研究摘要订阅。"}]},
  SOURCE_OPS:{approval:"需要管理员审批",scope:"公开信源健康与 Endpoint 配置",risk:"L2；探测操作必须审批，参数摘要留痕",output:"健康诊断与配置建议",placeholder:"例如：检查失败信源并给出不修改配置的修复建议。",presets:[
    {label:"信源健康检查",description:"诊断失败和低质量信源",objective:"检查当前公开信源健康状态，列出失败 Endpoint、可能原因和修复建议，不直接修改配置。"},
    {label:"来源质量审计",description:"识别单一来源占比与质量风险",objective:"审计当前信源质量与多样性，列出低质量、重复率高和单一来源占比风险。"}]},
  CRAWL_OPS:{approval:"需要管理员审批",scope:"采集任务、队列、重试与死信",risk:"L2；重试采集必须审批且可取消",output:"队列诊断与安全重试建议",placeholder:"例如：诊断采集积压和失败任务，但先不要执行重试。",presets:[
    {label:"采集队列诊断",description:"只读检查积压与失败",objective:"诊断当前采集队列积压、失败任务和死信情况，给出处理优先级，不执行重试。"},
    {label:"失败任务恢复",description:"定位可安全重试的任务",objective:"识别最近失败且可安全重试的采集任务，说明风险并在审批后执行重试。"}]}
};
function agentGuide(code:string){return AGENT_GUIDES[code]??{approval:"按风险等级判断",scope:"当前用户有权数据",risk:"仅允许白名单工具",output:"结构化运行结果",placeholder:"描述目标、范围和期望结果。",presets:[]};}
function toolLabel(value:string){return ({SEARCH_KNOWLEDGE:"检索知识库",READ_CONTENT:"读取公开内容",MANAGE_OWN_SUBSCRIPTION:"管理本人订阅",READ_SOURCE_HEALTH:"读取信源健康",PROBE_SOURCE:"探测信源",READ_CRAWL_STATUS:"读取采集状态",RETRY_CRAWL:"重试采集"} as Record<string,string>)[value]??value;}
function agentStatusLabel(value:string){return ({QUEUED:"排队中",WAITING_APPROVAL:"等待审批",RUNNING:"执行中",SUCCEEDED:"已完成",FAILED:"失败",CANCELLED:"已取消",PENDING:"待执行",SKIPPED:"已跳过",DENIED:"已阻止",APPROVED:"已批准",REJECTED:"已拒绝",EXPIRED:"已过期"} as Record<string,string>)[value]??value;}
function agentFailureLabel(value:string){return ({USER_CANCELLED:"用户取消",APPROVAL_EXPIRED:"审批过期",APPROVAL_REJECTED:"审批拒绝",EXECUTION_INTERRUPTED:"进程中断",TOOL_EXECUTION_FAILED:"工具执行失败"} as Record<string,string>)[value]??value;}
function agentDuration(run:AgentRun){if(!run.started_at)return "尚未开始";const end=run.completed_at?new Date(run.completed_at).getTime():Date.now();const seconds=Math.max(0,Math.round((end-new Date(run.started_at).getTime())/1000));return seconds<60?`${seconds} 秒`:`${Math.floor(seconds/60)} 分 ${seconds%60} 秒`;}
function formatAgentNumber(value:number){return new Intl.NumberFormat("zh-CN").format(value);}

function ProtectedWorkspace({ title, children }: { title: string; children: React.ReactNode }) { const { user, loading } = useAuth(); if (loading) return <div className="page-shell"><Empty text="正在检查会话…" /></div>; if (!user) return <div className="page-shell"><div className="permission-state"><span>需要登录</span><h1>{title}</h1><p>注册普通用户账号后即可使用收藏、订阅、研究与 Agent；管理端另需管理员权限。</p><Link className="button primary" href={`/login?returnTo=${encodeURIComponent(location.pathname)}`}>登录或注册</Link></div></div>; return children; }
function Empty({ text }: { text: string }) { return <div className="workspace-empty">{text}</div>; }
function WorkspaceNotice({ notice, onClose }: { notice: string; onClose: () => void }) { return <div className="agent-toast" role="status"><span>{notice}</span><button aria-label="关闭提示" onClick={onClose}>×</button></div>; }
function message(error: unknown) { return error instanceof ApiError ? error.message : error instanceof Error ? error.message : "请求失败"; }
function formatDate(value?: string) { return value ? new Intl.DateTimeFormat("zh-CN", { dateStyle: "short", timeStyle: "short" }).format(new Date(value)) : "—"; }
