export const featuredItems = [
  {
    time: "11:30",
    source: "OpenReview",
    sourceType: "论文",
    title: "OpenReview 新研究提出面向工具调用 Agent 的可验证轨迹评测框架",
    summary: "研究把复杂 Agent 任务拆成计划、工具参数、环境状态和结果证据四类检查点，用可复现轨迹判断长程任务是否真正完成。",
    reason: "评测对象从最终答案扩展到完整执行轨迹，对 Agent 的可靠性、审计和回归测试有直接工程价值。",
    tags: ["论文研究", "Agent", "评测"],
    score: 78,
  },
  {
    time: "10:10",
    source: "官网：天工短剧工作台",
    sourceType: "官网",
    title: "天工短剧工作台发布 Agent 智能分镜与无限画布双轨创作模式",
    summary: "通过导演 Agent 自动解析剧本、规划站位与机位，并支持多视角场景生成，解决角色和站位漂移问题。",
    reason: "产品已具备完整镜头组织和可控生成链路，是生成式视频从单点工具走向生产系统的典型案例。",
    tags: ["智能体", "产品更新", "视频"],
    score: 76,
  },
  {
    time: "09:40",
    source: "官网：MiniMax",
    sourceType: "官网",
    title: "MiniMax Code 2.0 桌面端焕新：底层架构全面升级",
    summary: "MiniMax Code 2.0 基于 Agent 框架重构桌面端，提升会话启动速度与长程复杂任务执行稳定性。",
    reason: "从代码到分析报告的链路更完整，适合关注 Coding Agent 与垂直行业 Agent 的开发者。",
    tags: ["MCP/工具", "产品更新", "编码"],
    score: 74,
  },
];
